### ISSUE TITLE
Add typescript type declaration to modules

### ISSUE THREAD

**Issue by danilofuchs** [coreui/coreui-free-react-admin-template#100]
I tried porting the theme to Typescript, following [this](https://javascriptplayground.com/react-typescript/) guide and I found that I would need to make type declaration for each of your modules.

**Comment by xidedix** [comment]
hi @danilofuchs - PR welcome!

**Comment by alex-deas** [comment]
@xidedix there's been a PR open since last October https://github.com/coreui/coreui-free-react-admin-template/pull/23

**Comment by alukach** [comment]
@xidedix Is there any suggestion for moving forward with #23 (e.g. is it reasonable to adapt it to V2? I'm not familiar with how different the two versions are)?  If not, I suggest we provide that reasoning and close that PR.  Would be great to see TypeScript support for the project, however I imagine it will take some management regarding steering PRs and Issues into the right direction.

**Comment by woothu** [comment]
v3 has TypeScript support for `@coreui/react` library
