### ISSUE TITLE
NavLink not loading the component

### ISSUE THREAD

**Issue by jitheshkt** [coreui/coreui-free-react-admin-template#101]
I want to load an additional page (which is not in _nav.js file since it has no purpose individually), kind of a detail page for a single record. Here what I have done so far:

in routes.js :

`{ path: '/waypoints/groups/view/:id', name: 'Waypoint Map', component: WayPointMap}`

and my link button is defined as follows:

`<NavLink to="/waypoints/groups/view/KIWu2o210o3">Mes utilisateurs</NavLink>`

It doesn't through any error, it changes the URL in the address bar, but it doesn't show the component. It still stays at the data grid page itself. What am I missing?

**Comment by woothu** [comment]
This issue is related to the `react-router` package
