### ISSUE TITLE
npm install not working due to package.json

### ISSUE THREAD

**Issue by JoeyKhd** [coreui/coreui-free-react-admin-template#104]
I am unable to npm install 

npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '...":false,"directories"'

**Comment by xidedix** [comment]
hi @JoeyKhd 
- Check what's your version of `node` and `npm`. Update when necessary.
- Sometimes things go wrong with `npm install` 
  - remove `node_modules` directory
  - remove `package-lock.json` file
  - then run `npm install` again 
- Sometimes npm cache gets confused.  You can reset it using: `npm cache verify` or `npm cache clean`

**Comment by dreeeyy** [comment]
still not working .. 
 
```
$ npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 4381 (84951498 bytes)
Index entries: 6913
Finished in 21.018s
```

```
$ npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2018-08-15T03_38_35_748Z-debug.log
```

```
$ npm install
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
```

**Comment by xidedix** [comment]
@dreeeyy
Looks like after `npm install` you've got warnings only, no errors.
