### ISSUE TITLE
Unable to use the spread operator

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [coreui/coreui-free-react-admin-template#105]
I have set the object in the state and want to use it as a data-attributes of the button so currently i am using it like as 

```
<button id="MakePayment_Button" className='btn btn-cn Save-Continue-Button pull-right' data-cb-type="checkout" {...this.state.attrubutes}>
                    Button Name
                </button>
```
debugger shows 'unexpxted token this"  message for the spread operator

**Comment by woothu** [comment]
This issue is not related to CoreUI features
