### ISSUE TITLE
please help me how to upgrade coreui pro to latest version

### ISSUE THREAD

**Issue by Siffre** [coreui/coreui-free-react-admin-template#108]
https://github.com/coreui/coreui-free-react-admin-template/issues/35#issuecomment-416644136

@xidedix

**Comment by theyeshu** [comment]
Same here. Please let me know as well.

**Comment by col-panic** [comment]
I just received an email with the text

CoreUI Pro Vue.js Extended License - updated!

I have recently updated some files associated with CoreUI Pro Vue.js Extended License. They're yours for free. The changelog is available on our website https://coreui.io/vue/changelog/ 

Funny is - the changelog linked, does not show any information on a March 2019 update - only v2.0.3 of Nov/18 ....

**Comment by AdnanBoota** [comment]
I'm also facing the issue to upgrade coreui-pro to latest version,

- is there any documentation to upgrade to latest version? any commands?
- or we just have to update the packages in package.json by reading from https://coreui.io/react/changelog/

I'm using yarn, any specific commands for yarn?

Thanks,
Adnan

**Comment by woothu** [comment]
When it comes to the template it is a resource to copy solutions from, so there is no need for migration.
