### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by mikepuglisi** [coreui/coreui-free-react-admin-template#109]
Am I allowed to build upon this coreui-free-react-admin-template and utilize it as the admin interface for a completely different software product that I charge money for? 

I'm not clear on the licensing, and I can't find any place to post questions.

**Comment by duttasantanu** [comment]
1. Can I also remove any "CoreUI Pro © 2018 creativeLabs." or "Powered by CoreUI Pro" and add my company name ? 
2. The phrase "can’t re-distribute the CoreUI as stock" means I cannot resell the template in any market place , even after updating. Am I right ?

**Comment by mrholek** [comment]
@duttasantanu 

1. Yes, you can.
2. Yes, you're right. In the past, we had some problems with developers who tried to sell templates based on CoreUI, but ThemeForest and wrapbootstrap removed those templates.

**Comment by duttasantanu** [comment]
Thank you @mrholek . I am planning to launch my product using Core ui free template.

**Comment by razuro** [comment]
Hi @mrholek, what about, if we do customization then sell it as a solution for our client? It's not on any marketplace.

**Comment by mrholek** [comment]
@razuro you can customize, and sell it as a solution for your client.
