### ISSUE TITLE
TypeError: Cannot read property 'pathname' of undefined

### ISSUE THREAD

**Issue by webdevabhi** [coreui/coreui-free-react-admin-template#112]
whenever i am adding children to any routes in _nav.js file.

it is throwing error :

`AppSidebarNav.activeRoute
node_modules/@coreui/react/es/SidebarNav.js:62
  59 | };
  60 | 
  61 | AppSidebarNav.prototype.activeRoute = function activeRoute(routeName, props) {
> 62 |   return props.location.pathname.indexOf(routeName) > -1 ? 'nav-item nav-dropdown open' : 'nav-item nav-dropdown';
  63 | };
  64 | 
  65 | AppSidebarNav.prototype.hideMobile = function hideMobile() {`

I am using mac os x and running on chrome.

My codes are :

`export default {
    items: [
        {
            name: "Dashboard",
            url: "/dashboard",
            icon: "icon-speedometer"
        },
        {
            name: "Users",
            url: "/users",
            icon: "icon-user",
            children: [
                {
                    name: "Feedback",
                    path: "/users/feedback"
                }
            ]
        }
    ]
};`

my Routes file containes:

`import React from 'react';
import Loadable from 'react-loadable'

import DefaultLayout from "./Layout";

function Loading() {
    return <div>Loading...</div>;
}

const Dashboard = Loadable({
  loader: () => import("./pages/Dashboard/Dashboard"),
  loading: Loading
});

const Users = Loadable({
    loader: () => import("./pages/Users/Users"),
    loading: Loading
})

const routes = [
    { path: '/', exact: true, name: 'Home', component: DefaultLayout },
    { path: '/dashboard', name: 'Dashboard', component: Dashboard },
    { path: '/users', exact: true, name: 'Users', component: Users },
    { path: '/users/feedback', exact: true, name: 'Users feedback', component: Users },
];

export default routes;`

**Comment by xidedix** [comment]
just guess:
`children: [ { name: "Feedback", path: "/users/feedback" } ] `
should be:
`children: [ { name: "Feedback", url: "/users/feedback" } ] `

**Comment by webdevabhi** [comment]
Hi @xidedix 

i have tried using url too.

Even with the empty array, the same error i am getting.
`{ name: "Users", url: "/users", icon: "icon-user",children: [ ] }`

**Comment by webdevabhi** [comment]
Hi,

Please response for this.

**Comment by abhishkekalia** [comment]
@webdevabhi install **history** dependencies

**Comment by webdevabhi** [comment]
Changed layout functional component to class component.
And it is working fine.

**Comment by toididau456** [comment]
@webdevabhi  Changed layout functional component to class component? I have same problem with you. You can materialize code??

**Comment by toididau456** [comment]
> Changed layout functional component to class component.
> And it is working fine.

Please! Reply me!!

**Comment by webdevabhi** [comment]
@toididau456 

Previously i have created a stateless functinal component.
After that i have changed to class extending components.

It solved my problem.

**Comment by ramads** [comment]
@webdevabhi 
I'm facing the same problem, could you please explain in more detail how you solved this problem?

in your case, which component you created as a functional component before? Is that a Users component? 
If so, I have already used class components, but I still got the same error message.

**Comment by webdevabhi** [comment]
@ramads 

i got one perfect solution.
You have to pass the props of react-router-dom which include location, history, etc.
Wheather your are keeping functional component or class component.
Please make sure you are passing the all the props including BrowserRoutern Props.

**Comment by ramads** [comment]
Thanks @webdevabhi 
solved my issue :)

**Comment by carauzs** [comment]
My 2 cents, for anyone having this problem, you can fix the issue by wrapping your functional component (the one using `AppSidebarNav` component) with `withRouter` HOC from react-router, withRouter will pass `location` prop to the wrapped component.

```
import React, { Suspense } from 'react';
import {
  AppHeader,
  AppSidebarHeader,
  AppSidebarForm,
  AppSidebarNav2 as AppSidebarNav,
  AppSidebarMinimizer,
  AppSidebarFooter,
  AppSidebar
} from '@coreui/react';
import * as router from 'react-router-dom';
import navigation from './_nav';

function BasePage(props) {
  return (
      <AppHeader fixed>
      </AppHeader>
      <div className="app-body">
        <AppSidebar fixed display="lg">
          <AppSidebarHeader />
          <AppSidebarForm />
            <AppSidebarNav navConfig={navigation} {...props} router={router} />
          <AppSidebarFooter />
          <AppSidebarMinimizer />
        </AppSidebar>
      </div>
    </div>
  );
}

export default router.withRouter(BasePage);
```

**Comment by ybizeul** [comment]
@xidedix Shouldn't that be somewhere in the doc ?
