### ISSUE TITLE
nomnom package has been deprecated

### ISSUE THREAD

**Issue by ampProjects** [coreui/coreui-free-react-admin-template#121]
Hi coreui team,

I wanted to install your free version for testing, and I can´t install dependencies because nomnom package has been deprecated.

Please have a look if you need other simillar package or remove this dependency of your project

This is the error after npm install:
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

Kind regards

**Comment by xidedix** [comment]
hi @ampProjects 
- what is your version of `webpack`?
- is it installed globally?
