### ISSUE TITLE
NPM Install failed for @CoreUI/Icons@0.3.0

### ISSUE THREAD

**Issue by qitma** [coreui/coreui-free-react-admin-template#126]
**Is this a bug report?**

Yes

### Did you try recovering your dependencies?

This is for the newest release (2.0.13). I try to **npm install** and i got message error for **@coreui/icons@0.3.0**. This is i got from log in npm
`3189 verbose stack Error: 404 Not Found: @coreui/icons@0.3.0
3189 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
3189 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
3189 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
3189 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
3189 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
3189 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
3189 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
3189 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
3189 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
3189 verbose stack     at runCallback (timers.js:705:18)
3189 verbose stack     at tryOnImmediate (timers.js:676:5)
3189 verbose stack     at processImmediate (timers.js:658:5)
3190 verbose cwd D:\qitma\Belajar\React\Test\my-project
3191 verbose Windows_NT 10.0.17134
3192 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3193 verbose node v10.13.0
3194 verbose npm  v6.4.1
3195 error code E404
3196 error 404 Not Found: @coreui/icons@0.3.0` 

### Which terms did you search for in User Guide?

NPM Install for coreui/icons

### Environment

Node 10.13.0
Npm 6.4.1
Windows 10 - 64

### Steps to Reproduce

(Write your steps here:)

1. Clone from `git clone https://github.com/coreui/coreui-free-react-admin-template.git my-project`
2. change to directory
3. exec command `npm install`

### Expected Behavior

Not Error

### Actual Behavior

Got some error
![react](https://user-images.githubusercontent.com/20252173/47757874-fec36680-dcda-11e8-9630-bff8800e6955.PNG)

### What i've try

I already try to **re-install node,js** , using command `npm cache clean --force` or `npm cache verify` but thats all not resolve my problem.
and i already check at [https://www.npmjs.com/package/@coreui/icons/v/0.3.0](url) package for coreui/icons is exist.

Thanks for your attention and sorry for my bad english.

**Comment by xidedix** [comment]
Cannot reproduce :|
Can anyone confirm this issue?

**Comment by qitma** [comment]
can anyone suggest solution ?
 i tried **npm set registry https://registry.npmjs.org/** but not work, and i try to install **coure ui icons** independently got same error..

**Comment by bhupeshpandey** [comment]
Even I am getting the same issue.

**Comment by bhupeshpandey** [comment]
Any suggested solution?

**Comment by xidedix** [comment]
What about creating a `.npmrc` file in the root of your project with:
`@coreui:registry=https://registry.npmjs.org/`
?

**Comment by qitma** [comment]
> What about creating a `.npmrc` file in the root of your project with:
> `@coreui:registry=https://registry.npmjs.org/`
> or
> `npm install --registry=https://registry.npmjs.com/ @coreui/icons`
> ?

i tried with your suggestion, and fortunately i got new error when i try with **npm install**

**7069 error Maximum call stack size exceeded**

any suggestion?

Thanks for your reply

**Comment by xidedix** [comment]
Which one you have tried?

**Comment by xang555** [comment]
try remove `~/.npmrc` and `npm install` again this way solved my problem when i reinstall package module

**Comment by qitma** [comment]
> Which one you have tried?
 i try with it 

> npm install --registry=https://registry.npmjs.com/ @coreui/icons

-----------------------------------------------------------------------
and right now i try it again ( clone new repo ) and npm install

and its work!!..

i dont change anything then i dont know why its work.
