### ISSUE TITLE
Webpack removed from core ui ?

### ISSUE THREAD

**Issue by JanBN** [coreui/coreui-free-react-admin-template#138]
There used to be webpack in this project. Where is it, or why it has been removed ?

**Comment by xidedix** [comment]
hi @JanBN 
We are using Webpack 4, and other tools, under the hood of [Create React App](https://facebook.github.io/create-react-app/). They are pre-configured with `react-scripts` and ready to use.

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive and answered above. Please comment and/or reopen if you feel the issue has not been resolved.
