### ISSUE TITLE
How to add icons from font awesome into AppSideBar?

### ISSUE THREAD

**Issue by Dan-Veinberg** [coreui/coreui-free-react-admin-template#139]
I downloaded font-awesome with npm and did 

`@import '../node_modules/font-awesome/css/font-awesome.css'` in index.scss which is located in the src folder.

I then tried to change the name of the icon in _nav.js. I tried changing the name to the following:

fas fa-stroopwafel
fa-stroopwafel
stroopwafel

This is an icon that is used in Coreui getting started tutorial. They did not work and I ended up with no icons.

Please help!

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive and answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Comment by christiantigre** [comment]
I have the same problem, how is the solutions

**Comment by nnnayeemm** [comment]
@Dan-Veinberg did you solve the problme?
If so, what is your solution?
