### ISSUE TITLE
cant overwrite :root sass colors

### ISSUE THREAD

**Issue by SteveTro** [coreui/coreui-free-react-admin-template#141]
i'm quite new to coreui and  cant solve it to change the default colors of the theme.
i red that i have to edit the _variables.scss, so i changed it like this:

`    $blue:    #02a19f;
    $primary: #02a19f;
    $font-family-sans-serif: 'Relative', serif;

    $colors: (
        --blue: $blue !important,
        --primary: $primary !important,
    ) !important;`

when i refresh the page there are 2 :root styles shown in the inspector.
the first one is the style with the default values:

`:root {
    --blue: #007bff;
    [...]
    --primary: #007bff;
}`

the second one is the style with my updated values

`:root {
    --blue: #02a19f;
    [...]
    --primary: #02a19f;

}`

the problem is, that all of the values are strikedthrough and not used.
Someone of you have a hint for me how i can fix that, to use my own colors?

**Comment by woothu** [comment]
Is this still an issue?
