### ISSUE TITLE
Documentation for ClassNames

### ISSUE THREAD

**Issue by Ghassen1992** [coreui/coreui-free-react-admin-template#142]
Hello, 
We are evaluating multiple React templates to use in a new project and we began with CoreUI.
Is thre any documentation for classNames in this template so we can customize components.
For Example I changed the header like this:

```
  <React.Fragment>
                <AppSidebarToggler className="d-lg-none" display="md" mobile />
                <AppNavbarBrand
                    full={{ src: logo, width: 89, height: 25, alt: 'CoreUI Logo' }}
                    minimized={{ src: sygnet, width: 30, height: 30, alt: 'CoreUI Logo' }}
                />
                <AppSidebarToggler className="d-md-down-none" display="lg" />       
                {/*<AppAsideToggler className="d-lg-none" mobile />*/}
            </React.Fragment>
```
And just after that the **AppSidebarToggler**  for the **AppNavbarBrand** just moved to the right because it was relative to other components in the Navbar. Is there a way to keep in the initial position.

![image](https://user-images.githubusercontent.com/13438744/50235984-41bec380-0387-11e9-9c8c-121b993b7c17.png)

Thanks a lot.

**Comment by xidedix** [comment]
hi @Ghassen1992 
What you ask for is the bootstrap utility classes actually. 
In this particular case, auto margins `mr-auto` will do.  
See: https://getbootstrap.com/docs/4.3/utilities/flex/#auto-margins
```
<AppSidebarToggler className="d-md-down-none mr-auto" display="lg" />
```

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive and answered above. Please comment and/or reopen if you feel the issue has not been resolved.
