### ISSUE TITLE
ES6 arrow functions not working

### ISSUE THREAD

**Issue by nsdev001** [coreui/coreui-free-react-admin-template#143]
Hello 

I have use es6 code.
but compile time given error.

```js
 handleChange = (e) => {
    this.setState({
      [e.target.id]: e.target.value
    })
  }
  handleSubmit = (e) => {
    e.preventDefault();
    this.props.signIn(this.state)
  }
```

here is error..

ERROR in ./src/containers/Login/Login.js
Module build failed: SyntaxError: e:/Project/Final_React_Redux/New folder/React_Firebase/src/containers/Login/Login.js: Unexpected token (11:15)

   9 |   //   password: ''
  10 |   // }
> 11 |   handleChange = () => {
     |                ^
  12 |     // this.setState({
  13 |     //   [e.target.id]: e.target.value
  14 |     // })

**Comment by JandersonConstantino** [comment]
I did make a test and this doesn't happen.
Could you give more details?
