### ISSUE TITLE
How to set left sidebar is minimized as default

### ISSUE THREAD

**Issue by ngoctai** [coreui/coreui-free-react-admin-template#145]
Hi all,
I want to show left sidebar minimized as default. I have tried to add minimized props to `AppSidebar` element as bellow `<AppSidebar fixed minimized>`. When i reload page i see it looks good but when i hover the mouse on it, it doesn't show child's menu level.
 It's behavior isn't the same when i click on  `AppSidebarMinimizer` element two times (that way works perfectly)

Thank all.

**Comment by nithinkashyapn** [comment]
Hey,

In `public/index.html`

Make body as this i.e., add the following class to it.

```
<body class="sidebar-minimized">
.
.
.
</body>
```

\- Nithin

**Comment by xidedix** [comment]
Hi @ngoctai, @nithinkashyapn - thanks for pointing this out!

Please update: 
- `@coreui/coreui` to `2.1.7` 
- `@coreui/react` to `2.1.4`  

```html
<AppSidebar fixed minimized>
...
</AppSidebar>
```
From now on `minimized` should work as expected.

Let us know if this helps.

**Comment by nithinkashyapn** [comment]
Thank you.

**Comment by ngoctai** [comment]
`<body class="sidebar-minimized">
.
.
.
</body>`

`<AppSidebar fixed minimized>
...
</AppSidebar>`

**Comment by xidedix** [comment]
Hi @ngoctai
it's intended to work without adding class to body.
what's your browser name/version?

**Comment by ngoctai** [comment]
> Hi @ngoctai, thanks for follow-up
> 
> it's intended to work without manual adding class `sidebar-minimized` to body.
> what's your browser name/version?

Yes,  you're right. That is my mistake, after clean cache that works perfectly as you said. Thanks a lot.

**Comment by fabiandeny** [comment]
Hi @xidedix, thanks for the minimized sidebar.
It's just that when the sidebar is minimized, the badges on sidebar items only show up when it's being hovered. They don't show up otherwise.
In `src/_nav.js`
```
...
{
    ...
    badge: {
        variant: 'warning',
        text: 'NEW',
    }
}
...
```
Is there a way to make them show?
Thanks

**Comment by xidedix** [comment]
Hi @fabiandeny 
you can overwrite css rule in `src/scss/_custom.scss` 
```css
.sidebar-minimized .sidebar .nav-dropdown-items .nav-link .badge {
  display: inline;
}
```
or sth like this

**Comment by fabiandeny** [comment]
Thanks @xidedix 
Got it working now.
Thanks for the super fast response
