### ISSUE TITLE
AppSidebarMinimizer does not work when taken to Top of menus

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [coreui/coreui-free-react-admin-template#146]
I have moved the AppSidebarminimizer to the top but it's not working. On first page load it shows the minimizer to the top and once a user clicks on it sidebar gets minimized and "Minimizer" moved to the footer.

Following is my Code in DefaultLayout.js 
```jsx
<AppSidebar fixed display="lg">
  <AppSidebarHeader />
  <AppSidebarMinimizer />
  <AppSidebarForm />
  <AppSidebarNav navConfig={this.state.navs} {...this.props} />
  <AppSidebarFooter>
    <DefaultSidebarFooter toggleDisclaimer={this.toggleDisclaimer}/>
  </AppSidebarFooter>  
</AppSidebar>
```
This works fine on local but on prod/dev minimizer behave differently.

On local, the sidebar gets class "sidebar-nav"  but on dev env its  "scrollbar-container sidebar-nav" So is the generated classed on dev after build are different and work differently?

**Comment by woothu** [comment]
It shouldn't work that way, which version of `@coreui/react` are you using?
