### ISSUE TITLE
Error: Cannot find module 'cssdb'

### ISSUE THREAD

**Issue by chandrashekhar729** [coreui/coreui-free-react-admin-template#149]
Failed to compile

./src/index.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
#Error: Cannot find module 'cssdb'

This error occurred during the build time and cannot be dismissed.

**Comment by xidedix** [comment]
hi @chandrashekhar729 

looks like `cssdb` dependency is missing 
(required by `react-scripts` -> `postcss-preset-env` -> `cssdb`)
- please make sure you have an access to `https://registry.npmjs.org/cssdb/-/cssdb-4.3.0.tgz`

Sometimes `npm install` fails  - you can try to remove:
-  `node_modules` directory
- `package-lock.json` file

and then install all dependencies again with `npm i`

**Comment by chandrashekhar729** [comment]
so what should i do i have try 2-3 times and every time i stuck with this now i have to install manually or add something in package.json

**Comment by xidedix** [comment]
@chandrashekhar729 
- do you have access to `https://registry.npmjs.org/cssdb/-/cssdb-4.3.0.tgz`?
- any error/logs on `npm install`?
- what's your version of: npm, nodejs, os?

**Comment by chandrashekhar729** [comment]
@xidedix 
thank you problem has been solved i have download manually and after that put all files in node module by my self now it's working properly thank you so much.....

**Comment by xidedix** [comment]
@chandrashekhar729 
- Thanks for the follow-up. I am glad you've found a workaround. 
- We still do not know what is the cause of this issue.

**Comment by nkusikevin** [comment]
Failed to compile
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Error: Cannot find module 'cssdb'

**Comment by nkusikevin** [comment]
can any one help fix that error please
