### ISSUE TITLE
How to add event on Nav item sidebar

### ISSUE THREAD

**Issue by realitas** [coreui/coreui-free-react-admin-template#154]
Hey Guys!

Is there a way to navItem prop for adding an Event? I want to call some function (logout function) when clicking the sidebar item.

Thanks in advance!

**Comment by pl-synth** [comment]
Hi!
This works for me :) in your `_nav.js` add this:
`import { signOut } from './services/amplify';`
and
```
    {
      name: 'Logout',
      url: '/logout',
      icon: 'fa fa-lock',
      attributes: {
        onClick: e => {
          e.preventDefault();
          e.stopPropagation();
          signOut();
        }
      }
    }
```

**Comment by irtzasuhail** [comment]
Hi,

I'm trying to do the same thing but its not working for me? 

`      {
      name: 'Hospital',
      url: '#',
      class: 'basket-item',
      attributes: {
        onClick: (e, item)=>{
           console.log(e, item) 
           alert("hi!");
          }
      }
    },`

**Comment by xidedix** [comment]
please update to  "@coreui/react": "^2.5.6",

**Comment by jainpradeep** [comment]
Hello,
It is not working with @coreui/react ^3.0.3

**Comment by gandarain** [comment]
> Hi,
> 
> I'm trying to do the same thing but it's not working for me?
> 
> ```js
>       {
>       name: 'Hospital',
>       url: '#',
>       class: 'basket-item',
>       attributes: {
>         onClick: (e, item)=>{
>            console.log(e, item);
>            alert("hi!");
>           }
>       }
>     },
> ```

same here, any update?

**Comment by jainpradeep** [comment]
In SIdebar.js 

Put a onclick handler on CSidebarNav element in the JSX

`      <CSidebarNav onClick={handleClickOpen} >

        <CCreateElement 
          items={navigation}
          components={{
            CSidebarNavDivider,
            CSidebarNavDropdown,
            CSidebarNavItem,
            CSidebarNavTitle
          }}
        />
      </CSidebarNav>`

Then create the handler the code

`
var handleClickOpen = function(event){
  console.log(event.target.childNodes[0].textContent)
}
`

Refer the clicked element like this 

`event.target.childNodes[0].textContent`

I hope I could help

**Comment by gandarain** [comment]
> In SIdebar.js
> 
> Put a onclick handler on the CSidebarNav element in the JSX
> 
> `<CSidebarNav onClick={handleClickOpen} > <CCreateElement items={navigation} components={{ CSidebarNavDivider, CSidebarNavDropdown, CSidebarNavItem, CSidebarNavTitle }} /> </CSidebarNav> `
> 
> Then create the handler the code
> 
> `var handleClickOpen = function(event){ console.log(event.target.childNodes[0].textContent) }`
> 
> Refer the clicked element like this
> 
> `event.target.childNodes[0].textContent`
> 
> I hope I could help

Thanks for your solution, finally I can create a logout function at my Side Bar js, like this,

in my navigation js,
````
export const sideBarStaffKasir = [
  {
    _tag: 'CSidebarNavItem',
    name: 'Dashboard',
    to: '/dashboard/home',
    icon: 'cil-speedometer',
    badge: {
      color: 'info'
    }
  },
  {
    _tag: 'CSidebarNavTitle',
    _children: ['Peminjaman']
  },
  {
    _tag: 'CSidebarNavItem',
    name: 'Lihat Daftar Peminjaman',
    to: '/dashboard/peminjaman/list',
    icon: 'cil-address-book'
  },
  {
    _tag: 'CSidebarNavTitle',
    _children: ['Pembayaran']
  },
  {
    _tag: 'CSidebarNavItem',
    name: 'Lihat Daftar Pembayaran',
    to: '/dashboard/peminjaman/list',
    icon: 'cil-address-book'
  },
  {
    _tag: 'CSidebarNavTitle',
    _children: ['Setting']
  },
  {
    _tag: 'CSidebarNavItem',
    name: 'Logout',
    icon: 'cil-settings'
  }
]
````

And in my sidebar
````
<CSidebarNav onClick={(event) => {
  if(event.target.childNodes[1].data === 'Logout'){
    logout()
  }
}}>
  {renderSideBar()}
</CSidebarNav>
````

**Comment by parth-silicon** [comment]
> Hi! This works for me :) in your `_nav.js` add this: `import { signOut } from './services/amplify';` and
> 
> ```
>     {
>       name: 'Logout',
>       url: '/logout',
>       icon: 'fa fa-lock',
>       attributes: {
>         onClick: e => {
>           e.preventDefault();
>           e.stopPropagation();
>           signOut();
>         }
>       }
>     }
> ```

It is working for me thanks...

**Comment by taher-shoker** [comment]
Hello,
It is not working with     "@coreui/angular": "~5.2.22",

**Comment by xidedix** [comment]
@taher-shoker 

You can add html `id` attribute to sidebar item, then use EventManager with addEventListener to call your custom function.
