### ISSUE TITLE
how should I redirect programmatically after login

### ISSUE THREAD

**Issue by saeidabr60** [coreui/coreui-free-react-admin-template#156]
if (authenticated)
    {
          window.location =  `Dashboard`;
    }
 But I get this URL in response
"http://localhost:3000/Dashboard#/".

I tried this code but it didn't  work  as well
  window.location =  `Dashboard`;

routing part is like this:
```jsx
<HashRouter>
  <Switch>
    <Route path="/Dashboard" name="Home" component={DefaultLayout} />
     <Route exact path="/" name="Login Page" component={Login} />
   </Switch>
</HashRouter>
```

**Comment by xidedix** [comment]
hi @saeidabr60 
maybe sth like this?
```js
if (authenticated) {
    this.props.history.push('/dashboard')
}
```
see also: 
- https://reacttraining.com/react-router/web/example/auth-workflow
- https://reacttraining.com/react-router/web/api/history

**Comment by saeidabr60** [comment]
> hi @saeidabr60
> maybe sth like this?
> 
> ```js
> if (authenticated) {
>     this.props.history.push('/dashboard')
> }
> ```
> 
> see also:
> 
> * https://reacttraining.com/react-router/web/example/auth-workflow
> * https://reacttraining.com/react-router/web/api/history

I faced fallowing error using
` this.props.history.push('/dashboard')`
"Unhandled Rejection (TypeError): Cannot read property 'push' of undefined"

as a temporary solution I used 
const path = `/` instead of const path = '/'
