### ISSUE TITLE
Onclick Redirect to a component passing props

### ISSUE THREAD

**Issue by Xifeat** [coreui/coreui-free-react-admin-template#157]
I'm on my Dashboard, 

> TL;TR
> If I click on a button on my dashboard I want to redirect my user to a new component passing props.

I have a list of things on my dashboard, 
When I click on my button, I retrieved the element ID from my list my **onClickDetail** function

After that I would like to redirect the user to a new component passing this element ID
How can I handle that ? 

App.js route: 
```jsx
<HashRouter>
  <Provider store={store}>
    <Switch>
      <Route exact path="/login" name="Login Page" component={Login} />
      <Route exact path="/register" name="Register Page" component={Register} />
      <Route exact path="/404" name="Page 404" component={Page404} />
      <Route exact path="/500" name="Page 500" component={Page500} />
      <PersistGate loading={null} persistor={persistor}>
        <Route path="/" name="Home" component={DefaultLayout} />
      </PersistGate>
    </Switch>
  </Provider>
</HashRouter>
```

my new route in route.js file is : 

`  { path: '/listDetail', exact: true, name: 'List Details', component: ListDetail}`

How Can I handle that ? 

I though adding  in app.js
`<Route path="/listDetail/:id" component={ListDetail}>
`

And add to my **onClickDetail** function 
<Link to={"/listDeail/" + id}>my list detail id : {id}</Link>

But it's not working.

**Comment by sumyathlaing** [comment]
Hi @Xifeat ,

Please try again by adding "id" in the route.js file.
{ path: '/listDetail/:id', exact: true, name: 'List Details', component: ListDetail}

and then get this id in the ListDetail component like that:
this.state= {
        id: props.match.params.id,
}
