### ISSUE TITLE
DataTable pagination integrate API calls

### ISSUE THREAD

**Issue by festum** [coreui/coreui-free-react-admin-template#158]
I have a pro license. My dataset is bigger than 50 millions. In this case, loading whole dataset is not a good idea. Is DataTables componets able to call API when switch page?

**Comment by woothu** [comment]
Our CDataTable component (available in version 3) doesn't support API calls but is made to integrate with API calls smoothly.

**Comment by ssomlk** [comment]
@festum Did you figure this out by any chance??
I have raised a similar issue
https://github.com/coreui/coreui-free-react-admin-template/issues/237
