### ISSUE TITLE
Highlight Option in Top Nav

### ISSUE THREAD

**Issue by dekhaus** [coreui/coreui-free-react-admin-template#160]
Hi

I'd like to be able to control when a top nav option is highlighted.

The simplest way of explaining my question is using the CoreUI Pro demo.  

The top nav in the CoreUI Pro demo has the following items ...

- Dashboard
- Users
- Settings

The default route ('/') corresponds to #/dashboard.  

What seems odd and out of place to me is that when the user navigates to #/dashboard - either by clicking the Dashboard top nav item or by just loading the site, the Users top nav item is highlighted.

Furthermore - if I click on the Users top nav item - the Users top nav item is highlighted.  This makes sense.  However - if I then click on the Dashboard top nav item - the Dashboard top nav item is not highlighted - the Users top nav item still is.  This doesn't make any sense to me.

How do I control which top nav item is highlighted and have that highlight state correspond directly to what item was last selected ?

Thanks
Dave

**Comment by xidedix** [comment]
Hi @dekhaus 
Thanks for the heads-up. You are right about the issue.
Please take a look at `src/containers/DefaultLayout/DefaultHeader.js`
```html
<Nav className="d-md-down-none" navbar>
  <NavItem className="px-3">
    <Link to="/" className="nav-link" >Dashboard</Link>
  </NavItem>
  <NavItem className="px-3">
    <Link to="/users">Users</Link>
  </NavItem>
  <NavItem className="px-3">
    <NavLink href="#">Settings</NavLink>
  </NavItem>
</Nav>
```
There are two separate link components used, that look and behave differently.
`<Link>` is a [React Router Link](https://reacttraining.com/react-router/web/api/Link)
`<NavLink>` comes from [Reactstrap](https://github.com/reactstrap/reactstrap/blob/4cda8bf93d7e5d5af20f37c6ac459f064c7ced75/src/NavLink.js)
The key point is that the styling is different. 
As a workaround, you can add `className="nav-link"` to `<Link>` component for Users.

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive and answered above. Please comment and/or reopen if you feel the issue has not been resolved.
