### ISSUE TITLE
Protected Routes

### ISSUE THREAD

**Issue by dekhaus** [coreui/coreui-free-react-admin-template#161]
Hi

I'm working on customizing an instance of the CoreUI Pro project ( coreui-pro-react-2019-03-13 ) so that instead of having all the sample widgets and what not - it has my code.

Perhaps I should 'back up' a moment.  My goal is it use CoreUI Pro dashboard as the UI for my project.  With that in mind - I believe I essentially have two choices on how to proceed  ...

1) start with a blank 'create-react-app' app and develop my UI/app using the CoreUI widgets
or
2) start with the complete CoreUI Pro admin dashboard app and remove functionality that I don't want and add my app specific functionality.

I've decided on choice #2.  

I've started adding my own routes and will need some of those routes to be protected.  

The app is using the latest react-router-dom.  I'm sure there are many ways of using react-router-dom - but my specific question is given how the app is currently set up, what's the most compatible way of adding route authorization/guards to the app ?

Thanks
Dave

**Comment by xidedix** [comment]
@dekhaus there is a 3rd option - begin with CoreUI Pro Starter and add necessary functionalities

**Comment by dekhaus** [comment]
Fair enough.

I still may consider that option - however, I may decide that its less work to continue down the 'path' I've chosen.   With that in mind - I still need to know, given how the app is currently set up, what's the most compatible way of adding route authorization/guards to the app ?

Thanks
Dave

**Comment by xidedix** [comment]
@dekhaus 
maybe this will help?
https://stackoverflow.com/questions/50502205/how-to-protect-routes-in-core-ui-react

**Comment by dekhaus** [comment]
Thx
Dave
