### ISSUE TITLE
sidebar and main width

### ISSUE THREAD

**Issue by aliebrahimi2015** [coreui/coreui-free-react-admin-template#164]
hi
how to Increase sidebar width to 250 or 300?
Also change the main width?

**Comment by xidedix** [comment]
@aliebrahimi2015
 for sidebar you can overwrite `$sidebar-width` scss variable

**Comment by aliebrahimi2015** [comment]
thanks
please sample code for sidebar and main
i am beginner

**Comment by xidedix** [comment]
@aliebrahimi2015 

src/scss/_variables.scss
```scss
// Variable overrides
$sidebar-width: 300px;
```
