### ISSUE TITLE
how to add or remove item from sidebar ?

### ISSUE THREAD

**Issue by AliSultanKhan** [coreui/coreui-free-react-admin-template#167]
Hi, How i can add and remove list item for sidebar . in which file i have to edit?
![image](https://user-images.githubusercontent.com/33395254/54878945-27e4bf00-4e55-11e9-9230-e3e652d58fbd.png)

**Comment by xidedix** [comment]
@AliSultanKhan 
look at `src/_nav.js`

**Comment by AliSultanKhan** [comment]
> @AliSultanKhan
> look at `src/_nav.js`

thank You for the quick reply. I have one more question if I want to show sidebar list item depending on my redux state how I can do this?

**Comment by xidedix** [comment]
hi @AliSultanKhan 
not exactly your case, but quite similar: #97

**Comment by ElanUtta** [comment]
You can modify the sidebar if you modularize your items in _nav, that way you add the items in a  variable according to your need

**Comment by kristoff2016** [comment]
There is any way to show items sidebar depend on user role ? Thank you

**Comment by woothu** [comment]
@kristoff2016 Such mechanism must be implemented by the user for now.

**Comment by Ravindrakumara** [comment]
how to change background color of sidebar?
