### ISSUE TITLE
Route clash

### ISSUE THREAD

**Issue by dekhaus** [coreui/coreui-free-react-admin-template#168]
Hi

I'd like to configure my app to recognize the following two routes ...

/requests/new   # route to take user to page to create a new Request
/requests/:id      # Request 'show' page - aka page renders the details for the Request with id = :id

The two path entries I've used are ...

{ path: '/requests/:id',name: 'Request Details', component: Request,  exact: true },
{ path: '/requests/new', name: 'Create Request', component: CreateRequest, exact: true },

The issue is that the router is treating the text 'new' in the 2nd route as the :id specified in the 1st route.   As you can see - I'm using the 'exact' property. 

How do I fix this ?

NOTE: Request is an object in my domain - it has nothing to do with Http.

Thanks
Dave

**Comment by xidedix** [comment]
@dekhaus 

what about (not tested):
```
{ path: '/requests/new', name: 'Create Request', component: CreateRequest, exact: true },
{ path: '/requests/:id',name: 'Request Details', component: Request },
```
