### ISSUE TITLE
Any plans for automated tests?

### ISSUE THREAD

**Issue by alexb-uk** [coreui/coreui-free-react-admin-template#17]
Hi,

I'm evaluating CoreUI, most likely the Pro extended licence, and I really like the approach you've taken over the majority theme forest templates. However was a little disappointed to see no automated tests for the React components.

Do you guys have any plans of adding tests or are they available as part of the Pro version?

Thanks a lot,

Alex

**Comment by david1983** [comment]
I think that you can use part of the tests from reactstrap https://github.com/reactstrap/reactstrap/tree/master/src/__tests__
... you should be able to cover most of the component used

**Comment by xidedix** [comment]
Hi @alexb-uk @david1983 
We are gradually introducing some more testing in v2.

Take a look here https://github.com/coreui/coreui-react
and there https://github.com/mrholek/coreui-free-react-admin-template/tree/v2.0.0

Keep in mind, it's an early alpha.
Please let us know, what do you think.

**Comment by alexb-uk** [comment]
Great stuff, I am also using Jest so I'll try to find some time to check through my code and see if any of the tests I've written are relevant / worth porting over to Core UI v2. If so will submit a PR.

Thanks

**Comment by AdnanBoota** [comment]
Thanks all for great suggestions for the tests, i was just wondering, what are the testing possibilities with the core-ui v3?
Any tests for core-ui v3, can we use reactstrap testing for core-ui v3 elements?

https://github.com/reactstrap/reactstrap/tree/master/src/__tests__
