### ISSUE TITLE
Have a dead recursive render in defaultLayout when added an AppBreadcrumb component in login.js page

### ISSUE THREAD

**Issue by zhonghuali** [coreui/coreui-free-react-admin-template#170]
- Operating system and version (Windows10)
- Browser and version (Chrome73)
- Reproduced steps:
1. go to coreui-free-react-admin-template source code, the version is core ui 2.1.7
2. add a component AppBreadcrumb  in `src/views/Pages/Login/Login.js`  
   `<AppBreadcrumb appRoutes={routes}/>` 
3. **changed HashRouter to BrowserRouter in app.js**
4. run `npm start`
5. open url http://localhost:3000/login in browser
6. then click the breadcrumb item HOME, it will forward to home component()
you will watch the browser was hang on, if you print out log of render in defaultLayout.js.
there are dead recursive render.

It only happens for BrowserRouter, HashRouter work fine.
the configuration in route.js seem like a recursive route path /.
but this issue doesn't happen on HOME breadcrumb click
Thanks

**Comment by zhonghuali** [comment]
the configuration in route.js seem like a recursive route path /.

but this issue doesn't happen on HOME breadcrumb click

**Comment by xidedix** [comment]
hi @zhonghuali thanks for reporting the issue

cannot reproduce with
`@coreui/coreui-free-react-admin-template` version `2.1.6`
`@coreui/coreui` version `^2.1.9`
`@coreui/react` version `~2.1.5`
`react` version `^16.8.5`
`react-router-dom` version `~4.3.1`

can anyone confirm this issue?

**Comment by xidedix** [comment]
@zhonghuali 
issue confirmed

to fix the issue please modify `src/routes.js` :
1. remove `import DefaultLayout from './containers/DefaultLayout';` 
2. change `Home` item in `routes` config array

from: 
```js
  { path: '/', exact: true, name: 'Home', component: DefaultLayout },
```
to:
```js
  { path: '/', exact: true, name: 'Home' },
```

---
Please let us know whether you are still facing the issue.

**Comment by zhonghuali** [comment]
It work fine with your workaround,Thank you very much!
