### ISSUE TITLE
popover: inconsistency between source and live preview

### ISSUE THREAD

**Issue by matthew-z** [coreui/coreui-free-react-admin-template#172]
MacOS
Chrome    Version 73.0.3683.86 (Official Build) (64-bit)
To Reproduce: simply clone this repo and `yarn run`

Problem:

In the live preview https://coreui.io/react/demo/#/base/popovers, popover can be dismissed by clicking anywhere on the page. However, in the actual react CoreUI template, the popover cannot be dismissed by it.

I understand that the reactstrap does not support dismissible popover feature, but why it is possible in the live preview ?

**Comment by xidedix** [comment]
hi @matthew-z 
according to reactstrap changelog:
_Popover will no longer dismiss when clicking away from it. To get this behaviour please use `trigger="focus"`. In 7.1.0, `trigger="legacy"` has been added to get the exact previous behavior._

live preview demo is based on `v6.5.0`

**Comment by matthew-z** [comment]
I see, thank you for your kind explanation :)
