### ISSUE TITLE
Can not override babel config (.babelrc) when try using decorator

### ISSUE THREAD

**Issue by pkitcha** [coreui/coreui-free-react-admin-template#173]
I would like to use mobx with coreui and I follow step to enable decorator from https://mobx.js.org/best/decorators.html

by Install support for decorators: **npm i --save-dev @babel/plugin-proposal-class-properties @babel/plugin-proposal-decorators**

and 

And enable it in  **.babelrc** file:

{
    **"plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true}],
        ["@babel/plugin-proposal-class-properties", { "loose": true}]
    ]**
}

But it doesn't work for me anyway  It look like that .babelrc was not loaded  when I have tried to change the babelrc with @babel/plugin-proposal-decorators", { "legacy": truedddd}] and it has no error about this.

Please help me.

**Comment by pkitcha** [comment]
after spend a day. I can resolve it by using "react-app-rewind" , "customize-cra" 

#1. install "react-app-rewind" , "customize-cra" 

 "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "customize-cra": "^0.2.12",
    "react-app-rewired": "^2.1.1",
    "react-scripts": "^2.1.8"
  }


#2 create "config-override.js" with syntax below

const {override, fixBabelImports, addLessLoader, addDecoratorsLegacy, useBabelRc} = require('customize-cra');
 
module.exports = override(
  addDecoratorsLegacy()
);


#3  change the scripts calling in package.json

"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "test:cov": "react-app-rewired test --coverage",
    "test:debug": "react-app-rewired --inspect-brk test --runInBand",
    "eject": "react-app-rewired eject"
  },

**Comment by bactoria** [comment]
I solved same issue.
thanks, so much!! 👍
