### ISSUE TITLE
Issue with IE 11 : Warning: The tag <main> is unrecognized in this browser

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [coreui/coreui-free-react-admin-template#174]
In the IE 11 browser <main> tag used in theme is showing an issue and not working.

In IE it is showing the error in console as '
Warning: The tag <main> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

**Comment by xidedix** [comment]
thanks  @AbhaysinghBhosale 

HTML5 semantic elements IE11: _Partial support refers to only the `<main>` element (added later to the spec) being "unknown", though **it can still be used and styled**._

see: https://caniuse.com/#feat=html5semantic

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive and answered above. Please comment and/or reopen if you feel the issue has not been resolved.
