### ISSUE TITLE
babel add plugin issue

### ISSUE THREAD

**Issue by prashantkorat14** [coreui/coreui-free-react-admin-template#175]
![image](https://user-images.githubusercontent.com/11851220/55886787-fba59e00-5bc9-11e9-8be5-d352695f7f61.png)

i already try to add " @babel/plugin-syntax-dynamic-import" on package.json and .babelrc file. but showing the same error.

can you please help me?

Thank you.

**Comment by Torrentus** [comment]
Experiencing the same issue here

**Comment by xidedix** [comment]
hi @prashantkorat14, @Torrentus 

1. what's your version of:
- `node` and `npm`
- `react` and `react-dom`
- `react-scripts`

2. also: make sure `create-react-app` isn't installed globally

**Comment by prashantkorat14** [comment]
> hi @prashantkorat14, @Torrentus
> 
> 1. what's your version of:
> 
> * `node` and `npm`
> * `react` and `react-dom`
> * `react-scripts`
> 
> 1. also: make sure `create-react-app` isn't installed globally

**Comment by prashantkorat14** [comment]
> hi @prashantkorat14, @Torrentus
> 
> 1. what's your version of:
> 
> * `node` and `npm`
> * `react` and `react-dom`
> * `react-scripts`
> 
> 1. also: make sure `create-react-app` isn't installed globally
hy @xidedix 
thanks for helping but i faced same issue after remove "create-react-app" from global.

this is closed by mistake.
version info.
- node: v11.3.0
- npm: v6.9.0
- react: 16.8.5
- react-dom: ^16.8.5
- react-script: ^2.1.8

**Comment by prashantkorat14** [comment]
I got a solution for this issue.

you have to add this plugin in webpack.config.js

**Comment by MohammedJaffar** [comment]
Hi @prashantkorat14  can you post the webpack.config.js file and required plugin version info.

Thanks in advance.

**Comment by MohammedJaffar** [comment]
Hi @prashantkorat14 , please help me to complete webpack implementation , i will face this issue more than a week , add the babel dynamic import plugins but it is not working .

![image](https://user-images.githubusercontent.com/8073735/56736819-c0d56580-6786-11e9-988a-d6118228ce3b.png)

![image](https://user-images.githubusercontent.com/8073735/56736857-d6e32600-6786-11e9-9a09-7ee7043c9957.png)


please help me  and thanks in advance.

**Comment by prashantkorat14** [comment]
create babel.config.js where package.json placed.

copy this code to 

module.exports = function(api) {
  console.log(api);

  api.cache(true);

  const presets = ["@babel/preset-env", "@babel/preset-react"];
  const plugins = [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-react-jsx"
  ];

  return {
    presets,
    plugins
  };
};


Please install the necessary dependency and also install node-sass
