### ISSUE TITLE
CoreUI React dropdown blurry

### ISSUE THREAD

**Issue by arhtudormorar** [coreui/coreui-free-react-admin-template#183]
When you click the user's avatar on the navbar, the dropdown appears blurry because of the translate3d. (check: https://coreui.io/react/demo/#/dashboard)
The solution to fix this is:

```js
import Popper from 'popper.js'
// see: https://github.com/twbs/bootstrap/issues/23590
Popper.Defaults.modifiers.computeStyle.gpuAcceleration = !(
  window.devicePixelRatio < 1.5 && /Win/.test(navigator.platform)
);
```

**Comment by woothu** [comment]
The issue seems to be resolved in Popper v2. Thanks for the report!
