### ISSUE TITLE
Uncaught TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by kalislami** [coreui/coreui-free-react-admin-template#185]
I have edited a several of menus in the sidebar, then I saved them on my git repository, then I cloned on a different PC.

then I run npm install and npm start

and I got this issue in the browser: 
https://www.screencast.com/t/UEzEa92XOg3l

can anyone help me?

thanks before

**Comment by xidedix** [comment]
hi @kalislami 

please try the following solution:
https://github.com/facebook/create-react-app/issues/7171#issuecomment-502797985
