### ISSUE TITLE
'Reference' is not exported from 'react-popper'.

### ISSUE THREAD

**Issue by Rand-om** [coreui/coreui-free-react-admin-template#189]
I'm getting this error after installing the template, any sugestion?
![image](https://user-images.githubusercontent.com/11022987/62983427-44ca6080-bdfd-11e9-9204-3f3a5479cfbd.png)

**Comment by natget21** [comment]
same issue here

**Comment by xidedix** [comment]
Hi

What's your version of: 
- react
- reactstrap
- @coreui/react

Where is your `DropdownToggler` located?

**Comment by apndo** [comment]
> 
> 
> Hi
> 
> What's your version of:
> 
>     * react
> 
>     * reactstrap
> 
>     * @coreui/react
> 
> 
> Where is your `DropdownToggler` located?

I have this:
React - 16.8.6
Reactstrap - 8.0.0
@coreui/react - 2.5.1

**Comment by xidedix** [comment]
there is a breaking change in reactstrap v8
- Modal, Dropdown{*}, PopperContent, Tabs: using new Context API, react-popper v. '1.3.3'

For the most basic use-case, as a workaround, try `UncontrolledDropdown` instead.

**Comment by umairrafiq1133** [comment]
@apndo Was you able to solve this? I am having same issue.

**Comment by woothu** [comment]
Dropdown components have been implemented in `@coreui/react` v3 by us, the issue is resolved.
