### ISSUE TITLE
Hover Tabs bug

### ISSUE THREAD

**Issue by theocerutti** [coreui/coreui-free-react-admin-template#191]
Hello,

Nav hover is bugged:

```
<Nav variant="tabs" defaultActiveKey="/home">
  <Nav.Item>
    <Nav.Link href="/home">Active</Nav.Link>
  </Nav.Item>
  <Nav.Item>
    <Nav.Link eventKey="link-1">Option 2</Nav.Link>
  </Nav.Item>
  <Nav.Item>
    <Nav.Link eventKey="disabled" disabled>
      Disabled
    </Nav.Link>
  </Nav.Item>
</Nav>
```

Result:

![Untitled](https://user-images.githubusercontent.com/44285344/68198201-2f289980-ffee-11e9-893b-1b28b511f424.png)

**Comment by xidedix** [comment]
Hi @theocerutti 

Looks like it's [react-bootstrap](https://react-bootstrap.github.io/components/navs/) issue.

CoreUI v2 for React uses [reactstrap](https://reactstrap.github.io/components/navs/) components, not `react-bootstrap`.
