### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-79_binding.node":

### ISSUE THREAD

**Issue by 198cad** [coreui/coreui-free-react-admin-template#195]
C:\Users\hilmen\Projects\coreui_x (master -> origin)
λ npm install

> node-sass@4.12.0 install C:\Users\hilmen\Projects\coreui_x\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-79_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
npm[17024]: c:\ws\src\signal_wrap.cc:159: Assertion `(new_handler_count) >= (0)' failed.
 1: 00007FF74781021F napi_wrap+124591
 2: 00007FF7477B0296 v8::base::CPU::has_sse+35542
 3: 00007FF7477B05B3 v8::base::CPU::has_sse+36339
 4: 00007FF747734393 v8::internal::MicrotaskQueue::microtasks_policy+37795
 5: 00007FF7477339D4 v8::internal::MicrotaskQueue::microtasks_policy+35300
 6: 00007FF7477FC20D napi_wrap+42653
 7: 00007FF74780A62A napi_wrap+101050
 8: 00007FF74777C1CB v8::internal::interpreter::BytecodeArrayWriter::source_position_table_builder+29851
 9: 00007FF7477D8080 node::Start+288
10: 00007FF7476966FC RC4_options+339452
11: 00007FF7484D7678 v8::internal::SetupIsolateDelegate::SetupHeap+1290008
12: 00007FFA8BDF7BD4 BaseThreadInitThunk+20
13: 00007FFA8C26CED1 RtlUserThreadStart+33
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-sass@4.12.0 install: `node scripts/install.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hilmen\AppData\Roaming\npm-cache\_logs\2019-12-07T02_19_20_306Z-debug.log

**Comment by xidedix** [comment]
@198cad 
What's your version of node / npm?
```bash
node -v & npm -v
```
