### ISSUE TITLE
Double Routing malfunctioning

### ISSUE THREAD

**Issue by TATARPRO** [coreui/coreui-free-react-admin-template#200]
In the `App.js` where the routes and layouts are registered, the only layout created which is the `DefaultLayout` and then other primary pages which are not part of the dashboard. I stumbled over a case where I had to create two layouts for the app and this gave me a headache.
I tried this
```
<BrowserRouter>
          <React.Suspense fallback={loading()}>
            <Switch>
              <Route exact path="/login" name="Login Page" render={props => <Login {...props}/>} />
              <Route exact path="/register" name="Register Page" render={props => <Register {...props}/>} />
              <Route exact path="/404" name="Page 404" render={props => <Page404 {...props}/>} />
              <Route exact path="/500" name="Page 500" render={props => <Page500 {...props}/>} />
              <Route path="/home" name="Home" render={props => <HomeLayout {...props}/>} />
              <Route path="/dashboard" name="Admin Dashboard" render={props => <DefaultLayout {...props}/>} />
            </Switch>
          </React.Suspense>
      </BrowserRouter>
```
So in this case, when the application starts, it does not find a default or root route so it is left blank. In this case, I can navigate to both layouts correctly but I have to manually put the route prefix before it navigates to the route definition.
I then had to remove the `/home` from the `HomeLayout` but this time, only the home layout then works. The other layout then is disabled. Is there a patch to this?

**Comment by woothu** [comment]
Just make a redirect from '/' to the desired route. Notice that this is `react-router` related issue.
