### ISSUE TITLE
Breadcrumb parent with :id

### ISSUE THREAD

**Issue by snobrdinrtiste** [coreui/coreui-free-react-admin-template#203]
is there a way to add the :id to a parent breadcrumb when i got into a child route with another :id ?
for instance:  
i'm currently in route "../project/1"
then i click a link to go to "../project/task/1"  (i need the "project" breadcrumb to contain the link "../project/1" instead of having "../project")

there is a another post about breadcrumbs and dynamic urls a way back and seems to me that is been fixed so maybe i'm doing something wrong?  or is there an example which i can refer to?  i'm thinking i'm missing something in my routes.js

**Comment by xidedix** [comment]
Hi @snobrdinrtiste 

Do you mean something like that?

https://coreui.io/react/demo/#/users
https://coreui.io/react/demo/#/users/4

**Comment by snobrdinrtiste** [comment]
Hi @xidedix 
It was my stupid error ... my routes.js was correct but i totally forgot that I didn't put in the dynamic id in my <Link>
so my entry in the routes.js is like this:
`{ path: '/base/pmt/project/:id/task/:id', exact: true, name: 'Task', component: PMTTask2 }`

and my <Link> was this... 
`<Link to={'/base/pmt/project/task/' + obj.taskId}>`

once i made the necessary changes to this:
`<Link to={'/base/pmt/project/' + this.state.theprojectid + '/task/' + obj.taskId}>`

it just worked!

**Comment by snobrdinrtiste** [comment]
Thanks for the quick reply!!!
