### ISSUE TITLE
 Warning: Invalid value for prop `dispatch`

### ISSUE THREAD

**Issue by enyachoke** [coreui/coreui-free-react-admin-template#206]
Am having this issue when I connect state to my components. Am kind new to react and this is my first project to help me learn

- Mac OS 10.14.6  Mojave 
- Chrome 80.0.3987.132 (Official Build) (64-bit)
```
index.js:1 Warning: Invalid value for prop `dispatch` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior
    in div (created by ScrollBar)
    in ScrollBar (created by AppSidebarNav2)
    in AppSidebarNav2 (at DefaultLayout.js:55)
    in Suspense (at DefaultLayout.js:54)
    in div (created by AppSidebar)
    in ClickOutComponent (created by AppSidebar)
    in AppSidebar (at DefaultLayout.js:51)
    in div (at DefaultLayout.js:50)
    in div (at DefaultLayout.js:44)
    in DefaultLayout (created by ConnectFunction)
    in ConnectFunction (at App.js:29)
    in Route (at App.js:27)
    in Switch (at App.js:23)
    in Suspense (at App.js:22)
    in Router (created by HashRouter)
    in HashRouter (at App.js:21)
    in App (at src/index.js:15)
    in Provider (at src/index.js:14)
```

**Comment by xidedix** [comment]
@enyachoke 
I have a feeling this is redux related. For example redux `connect` creates `dispatch` prop.
Maybe somewhere in the code props are spread - sth like `<div {...props}>`.
Your code would be handy to tell more.

**Comment by enyachoke** [comment]
Thanks @xidedix  that pointed me in the right direction. So basically used your react demo as a starting point. And  at this line https://github.com/enyachoke/nyumbu-data/blob/master/src/containers/DefaultLayout/DefaultLayout.js#L55. The props are passed using a spread operator which is just fine when the props are empty. If you introduce https://github.com/enyachoke/nyumbu-data/blob/master/src/containers/DefaultLayout/DefaultLayout.js#L100 then the warning happens. So for now am not going to pass props to the app nav. 

On a different my learning from this is when passing props using spread is not exactly a good idea?😀

**Comment by woothu** [comment]
It is ok to use spread when the object you spread is predictable :)
