### ISSUE TITLE
Login page redirect to login#/dashboard

### ISSUE THREAD

**Issue by Daornit** [coreui/coreui-free-react-admin-template#207]
i have been recently donwloaded you guys project. when i check to path URLs to create a new page. i discovered that when i goto the localhost:3000/login it automatically redirect to localhost:3000/login#/dashboard and it renders DefaultLayout component. I wanna direct render Login page but It won't direct there.Is there any automatic redirect path? and any help would be great.
In a app.js file, there is a react-dom-router Switch but it does not work properly.
![Screenshot from 2020-03-24 13-20-18](https://user-images.githubusercontent.com/34941714/77393490-16bbee80-6dd8-11ea-9746-81cb2dd882eb.png)

**Comment by xidedix** [comment]
see: https://github.com/coreui/coreui-free-react-admin-template/issues/113#issuecomment-424246135

**Comment by mojojojo20** [comment]
I changed HashRouter to BrowserRouter to get red of "#" and then used this -  

```
<BrowserRouter>
     <React.Suspense fallback={loading()}>
            <Switch>
              <Route exact path="/register" name="Register Page" render={props => <Register {...props}/>} />
              <Route exact path="/404" name="Page 404" render={props => <Page404 {...props}/>} />
              <Route exact path="/500" name="Page 500" render={props => <Page500 {...props}/>} />
              <Route path="/admin" name="Home" render={props => <DefaultLayout {...props}/>} />
              <Route exact path="/" name="Login Page" render={props => <Login {...props}/>} />
            </Switch>
   </React.Suspense>
</BrowserRouter>
```
