### ISSUE TITLE
Sidebar Scroll Bug 

### ISSUE THREAD

**Issue by karthiknmenon** [coreui/coreui-free-react-admin-template#208]
The sidebar doesn't move up or down when "pages" is selected.

How to recreate the problem- 

1. On the dashboard, click on Pages
2. Then scroll down on the sidebar
3. Close pages (without scrolling sidebar to the top)
4. Try scrolling up

Operating System - Mac OS
Browser - Safari

Below is the screenshot, when I open "pages" - 
![Screen Shot 2020-04-04 at 8 42 54 PM](https://user-images.githubusercontent.com/41678651/78454349-2f1fe900-76b5-11ea-9e00-9ddc639f120b.png)

Now, after I close pages, the sidebar doesn't auto scroll to the top, or let me scroll up. Below is the screenshot of the issue- 
![Screen Shot 2020-04-04 at 8 43 04 PM](https://user-images.githubusercontent.com/41678651/78454370-57a7e300-76b5-11ea-8fc9-c2f521a54a72.png)

**Comment by ybizeul** [comment]
Maybe related, in Safari, the bottom of the bar slowly moves up when using the scroll wheel

**Comment by johnnytolengo** [comment]
if you have an option in the bottom of the menu and then you click to open it, it opens but the down new opened items are hidden, you have to scrol down to see them. I consider it as a bug. 
I think in that case the whole bar has to move up hand show the child menues.
By the way the colors/design structure of the menu is very messy, sometime you can't easy recognize parents of children objects.
