### ISSUE TITLE
How to use grid Editing in core ui React JS

### ISSUE THREAD

**Issue by kheipl** [coreui/coreui-free-react-admin-template#211]
I am going to create invoice application in Core-ui React JS.In my invoice entry I have two information Invoice Header and invoice Details.As Header part I can use core UI "Forms" control.For Invoice Details I am going to use "grid Editing".So I would like to know how to use grid Editing in core ui React JS

**Comment by woothu** [comment]
We don't have the grid editing component/feature. You need some external library for that.
