### ISSUE TITLE
dropdown menu top 

### ISSUE THREAD

**Issue by junaooaks** [coreui/coreui-free-react-admin-template#212]
hey guys
how I can  use the dropdown menu to the top right (setting payment lock account) open on the content the application (center dashboard)

I the model contact and 
on my 
index.js        import Contact from "./Contact";
route.js      { path: "/contact", name: "Contact", component: Contact },
DefaultHeader.js.  ```<DropdownItem href="/contact">
                                <i className="fa fa-envelope-o"></i> Contact Us
                            </DropdownItem>   ```

**Comment by mojojojo20** [comment]
@junaooaks Try importing {Link} from react-router-dom and use it as follows - 
```
<Link to="/contact"> <DropdownItem> <i className="fa fa-envelope-o"></i> Contact Us </DropdownItem> </Link>
