### ISSUE TITLE
Build size is too large - 23 mbs

### ISSUE THREAD

**Issue by imhashir** [coreui/coreui-free-react-admin-template#214]
The final build is too large. I checked the build folder and looks like it's not optimizing the bundle. The build/static/media contains all flags SVGs. And I haven't used a single flag SVG in my project.

**Folder sizes:**

- build/static/css - 905 KB
- build/static/js - 14 MB
- build/static/media - 7.8 MB

I can delete the `media` folder straight away and still get my app running successfully on s3. But it's still 14 MB in size. Is this an expected behavior? All those assets in `media` folder are not used in my app. I can add a command to `npm run build` to delete the `media` folder automatically but I guess there should be a better way to handle this. 

Is there something that I am missing with the build process?

Here's the package.json file:

```
{
  "name": "@coreui/coreui-free-react-admin-template",
  "version": "2.6.0",
  "description": "CoreUI React Open Source Bootstrap 4 Admin Template",
  "author": "Łukasz Holeczek",
  "homepage": "https://coreui.io",
  "copyright": "Copyright 2017-2019 creativeLabs Łukasz Holeczek",
  "license": "MIT",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git@github.com:coreui/coreui-free-react-admin-template.git"
  },
  "dependencies": {
    "@babel/polyfill": "^7.8.3",
    "@coreui/coreui": "^2.1.12",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.3.1",
    "@coreui/icons": "0.3.0",
    "@coreui/react": "^2.5.1",
    "@material/react-snackbar": "^0.15.0",
    "aws-amplify": "^2.2.6",
    "axios": "^0.19.2",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "classnames": "^2.2.6",
    "core-js": "^3.1.4",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "faker": "^4.1.0",
    "flag-icon-css": "^3.3.0",
    "font-awesome": "^4.7.0",
    "node-sass": "^4.13.1",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-app-polyfill": "^1.0.1",
    "react-chartjs-2": "^2.7.6",
    "react-cookie": "^4.0.3",
    "react-dom": "^16.8.6",
    "react-dropzone": "^10.2.1",
    "react-loading": "^2.0.3",
    "react-router-config": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-test-renderer": "^16.8.6",
    "reactstrap": "^8.0.0",
    "simple-line-icons": "^2.4.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.8.4",
    "@babel/preset-env": "^7.8.4",
    "react-scripts": "^3.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "deploy": "npm run build && aws s3 sync build/ s3://mys3bucket",
    "test": "react-scripts test",
    "test:cov": "npm test -- --coverage --watchAll=false",
    "test:debug": "react-scripts --inspect-brk test --runInBand",
    "eject": "react-scripts eject"
  },
  "bugs": {
    "url": "https://github.com/coreui/coreui-free-react-admin-template/issues"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 9",
    "not op_mini all"
  ],
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}",
      "!**/*index.js",
      "!src/serviceWorker.js",
      "!src/polyfill.js"
    ]
  },
  "engines": {
    "node": ">=8.10",
    "npm": ">=6"
  }
}

```

**Comment by Gadeoli** [comment]
@imhashir, hello.
I'm having the same question.
I'm a begginner with reactJS. 
I choose it to a project with some dozens of forms and my build are to big too :/

**Comment by imhashir** [comment]
As a temporary workaround, I am removing build/static/media folder right after running build command. 

`npm run build && rm -rf build/static/media`

It saves me about 7.8 MB. But it's still a whole 14 MB.

**Comment by Gadeoli** [comment]
> As a temporary workaround, I am removing build/static/media folder right after running build command.
> 
> `npm run build && rm -rf build/static/media`
> 
> It saves me about 7.8 MB. But it's still a whole 14 MB.

You can remove some icons references in App.scss
This could save 1 or 2 MB

I removed font awesome 4.7 and installed 5.13 for core ui's nav icons.
In my components i'm using a font awesome library to import just necessary icons.

**Comment by woothu** [comment]
The template is a resource to copy solutions from, not the ready project. It is bloated with features.

There is available `coreui-pro-react-admin-template-starter`, which initially weights about 1MB (without js maps, before gzip), and is good staring point to develop application. It is available in the PRO version.
