### ISSUE TITLE
AppSidebarNav2 children hidden if its past 30 items

### ISSUE THREAD

**Issue by stevedhs** [coreui/coreui-free-react-admin-template#215]
Firstly the scroll isn't coming when the list is over the view, For a fix, I have a div with overflow:auto around the nav bar and that seems to be okay as sometimes 2 scroll bar appears.

Secondly, I have 10 items and one of the item have 50 Children ,  only 30 Children items are displayed and the remaining are hidden in the NavBar.

![image](https://user-images.githubusercontent.com/55526685/79303495-9e050980-7f21-11ea-8030-a7a90652c9c1.png)

**Comment by woothu** [comment]
Does this problem still occur in `@coreui/react` v3?
