### ISSUE TITLE
Confused by documentation, where do I start ?

### ISSUE THREAD

**Issue by ybizeul** [coreui/coreui-free-react-admin-template#219]
Trying to figure out where to start.

On the github main page I figured "Usage" might be a good starting point.

Well, link doesn't work. So as it's between "Installation" and "What's included" I guess "Usage" actually means "Create React App" section. So I did that. Standard `npm` stuff, great.

The examples kind of works little bugs here and there bug I could live with it and support seem to be active.

Then I want to figure out how to do my own dashboard. But it seems none of the components used in the examples are documented anywhere (things like `AppSidebar`, `AppHeader`, all the `App*` stuff).

So I started working implementing my own components, like the documentation [here](https://coreui.io/react/) suggests. It seemed very promising at first sight, but I eventually got frustrated and wondering if I was doing the right thing. Usually with React modules, users get ready to use components, it felt like I am doing something wrong.

And still, nothing about `App*` components in there. I can understand that if that was all part of the example repository, but `App*` components are actually part of the distribution, it looks like I should be able to use them, but without documentation I don't feel like poking around the source code.

After all this time I think I can boil it down to : is there a documentation for the `coreui-react` project ? EVen though I have a fairly good background in web development, I'm kinda new to modern framework, a lot of frustartion comes from that as well, and after reading the CoreUI manifesto, I felt like the approach is the right fit.

Thank you.

**Comment by woothu** [comment]
We highly recommend using version 3, which is currently developed and is much better documented
https://coreui.io/react/docs/

**Comment by ybizeul** [comment]
You mean the upcoming version ?

![image](https://user-images.githubusercontent.com/182035/85410606-9720f580-b567-11ea-8290-90a7ccc71690.png)

**Comment by woothu** [comment]
This description is obsolete, it is on stable version   couple od weeks (3.0.4 version)
