### ISSUE TITLE
Is there a way to customize SVG icon in the sidebar

### ISSUE THREAD

**Issue by ybizeul** [coreui/coreui-free-react-admin-template#220]
#80 is a mention of this.

It's not immediatly obvious how we can reference our own svg file to customize icons in the Sidebar. Is it natively supported or is there a hack around it ?

By the way, the icon web site show pretty much every icon with the wrong name.

**Comment by SReaver** [comment]
I also need to use custom SVG icons in the sidebar. How I can do it?

**Comment by woothu** [comment]
Are you asking about version 2 or 3 of the template?

**Comment by ybizeul** [comment]
Probably v2 :

![image](https://user-images.githubusercontent.com/182035/85410721-ba4ba500-b567-11ea-820a-20ae38b03eac.png)

**Comment by woothu** [comment]
The current version od library is 3.0.4, this description is obsolete

**Comment by woothu** [comment]
When it comes to v2, here is the function which computes icon:

https://github.com/coreui/coreui-react/blob/2dc4521d7e43dd5cc48d0ed184dfb03ca765207a/src/SidebarNav2.js#L171

so to pass svg you can try `icon: { img: { src: 'svg_source'} }`

**Comment by fmandres92** [comment]
I have the same issue. 
This is my version: 
    "@coreui/coreui": "2.1.12",
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "1.3.1",
    "@coreui/icons": "0.3.0",
    "@coreui/react": "2.5.1",

And this is the implementation :

  icon: {
        img: {
          src: 'new-compras.svg'
        }
    },

new-compras.svg is at the same level.

What can i do ?.
Please help me

**Comment by alextaymx** [comment]
I have the same issue as above, can anyone please help on using custom icons / CoreUI freeSet icons in the navbar? any icon other than the predefined ones couldn't be used. Please help
