### ISSUE TITLE
Unable to add  "breadcrumb-menu" inside  <AppBreadcrumb appRoutes={routes} router={router}>

### ISSUE THREAD

**Issue by bdayam** [coreui/coreui-free-react-admin-template#227]
I am using DefaultLayout.js, I just want to add "breadcrumb-menu" in <AppBreadcrumb appRoutes={routes} router={router}>, I am unable to find a way to add "breadcrumb-menu", please help me

**Comment by woothu** [comment]
Which versions of template and `@coreui/react` library are you using?
