### ISSUE TITLE
Couldn't change the logo in coreui 3

### ISSUE THREAD

**Issue by sasimohan** [coreui/coreui-free-react-admin-template#228]
As coreui 3 react template is brand new and completely using functional components, that's great. But logo is developed with lot of complication(May be as I'm newbie it may be tough for me). Is there any possible way to change the logo code. I could understand that CIcon is a component developed by coreui team. Also in responsive view there is another svg logo displayed. Can someone help me how could you change both the logo that shown in below screenshots.

The one present in sidebar:
![image](https://user-images.githubusercontent.com/63223048/85723151-95defc80-b710-11ea-8286-b05c876e10fc.png)

The one that displays while screen size changes:
![image](https://user-images.githubusercontent.com/63223048/85723272-b444f800-b710-11ea-87b4-778694e236ef.png)

_Note: Taken these screenshots from the coreui demo page, but still I have a local repository as well_

        <CIcon
          className="c-sidebar-brand-full"
          name="logo-negative"
          height={35}
        />
        <CIcon
          className="c-sidebar-brand-minimized"
          name="sygnet"
          height={35}
        />

**Comment by woothu** [comment]
In `src/assets/icons` those icons are defined then they are imported in `index.js` and so they are available globally.

You can convert your logo to js or just link to your logo svg through `src` prop in `CIcon` component
https://coreui.io/react/docs/components/CIcon

**Comment by sasimohan** [comment]
Thank you so much for the clarification @woothu I have made the changes in the existing svg file. As I'm not well versed in creating custom svg, used svg text to develop my logo text.

**Comment by sscarduzio** [comment]
src prop in CIcon was removed, what should we do?
