### ISSUE TITLE
sidebar not working after updating store file

### ISSUE THREAD

**Issue by turkdoktoru** [coreui/coreui-free-react-admin-template#230]
Hello,

I'm using core-ui-react version 3.20. I made a change to the ./store file, but sidebar doesn't work. What could be the reason for this? how can i solve it?
You can find the ./store file I changed below. Can you help with the subject?

- Operating system and version: Linux
- Browser and version: Opera latest

`

     
![sc](https://user-images.githubusercontent.com/42943216/86088337-cfb45800-baae-11ea-9755-8b7a3b788bba.png)

import {applyMiddleware, combineReducers, compose, createStore} from "redux";
     import customerReducer from "./components/helpers/reducers/customerReducer";
     import userReducer from "./components/helpers/reducers/userReducer";
     import appointmentsReducer from "./components/helpers/reducers/appointmenstReducer";
     import thunk from "redux-thunk";

     const initialState = {
       sidebarShow: 'responsive'
     };
     const changeStateReducer = (state = initialState, { type, ...rest }) => {
       switch (type) {
         case 'set':
           return {...state, ...rest };
         default:
           return state
       }
     };
     const rootReducers = combineReducers({
       customerInfo: customerReducer,
       account_profile: userReducer,
       appointmentsList: appointmentsReducer,
       changeState: changeStateReducer
     });
     const allEnhancers = compose(
       applyMiddleware(thunk)
     );
     const store = createStore(
       rootReducers,
       allEnhancers
     );

     export default store
`

**Comment by woothu** [comment]
1. This issue is not related to CoreUI
2. This issue is not about any problem in 'redux'

That means it is a simple debugging issue.
