### ISSUE TITLE
some icons not working

### ISSUE THREAD

**Issue by saldhyyoga** [coreui/coreui-free-react-admin-template#231]
Hello,i'm working with core ui 3.0 version. I try to change nav icon. but some icon not working.
the picture is bellow. any solutions ?

![Screenshot (28)](https://user-images.githubusercontent.com/47841587/86097195-82e87580-bade-11ea-9f64-52e64ea3b18a.png)

**Comment by woothu** [comment]
You have to import 'cilWallet' icon or the whole 'freeSet' and include it in React.icons object

**Comment by saldhyyoga** [comment]
import {cilWallet } from '@coreui/icons'

export default [
  {
    _tag: 'CSidebarNavItem',
    name: 'Transaction',
    to: '/dashboard',
    icon: 'cil-speedometer'
  }
]

i write code above but still not working

**Comment by woothu** [comment]
you need to include the icon in `React.icons` object (it is in `src/index.js` and icons are bundled in `src/assets/icons`)

**Comment by dnorton29** [comment]
Sorry, I know this is closed, but is there any documentation for why we need to add it to the `React.icons` object?

**Comment by woothu** [comment]
CIcon docs are not extensice yet: https://coreui.io/react/docs/components/CIcon

It is a way we have established for icons to be available globally. You can also import them every time and pass through the `content` prop.
