### ISSUE TITLE
Sidebar nav does not reload page

### ISSUE THREAD

**Issue by kevinpranoto** [coreui/coreui-free-react-admin-template#232]
The Sidebar nav does not seem to reload the page when navigating back to the parent route or to itself.

Say I have this route configured:

```
    { path: '/parent', exact: true, name: 'Parent', component: Resource,
      routes: [
      { path: '/child', exact: true, name: 'Child', component: Resource,
        routes: [
          { 
            path: '/grandchild', exact: true, name: 'Grandchild', component: Resource, 
            routes: [
              { path: '/greatgrandchild', exact: true, name: 'Greatgrandchild', component: Resource },
            ] 
          }
        ] 
      },
      { path: '/other', exact: true, name: 'Otherchild', component: Resource }
    ] 
  }
```

CoreUI does not reload the page when I am in Child, then I navigate to Parent on the sidebar. Using the browser 'back' button seems to work fine. Is this a bug or am I making a mistake somewhere?

**Comment by woothu** [comment]
The sidebar is not reloading anything, the router is reloading page. The Sidebar Nav only contains router links like any other component could. This is `react-router` related issue.
