### ISSUE TITLE
`SyntaxError: Cannot use import statement outside a module` in `@coreui/utils/src/index.js:1`

### ISSUE THREAD

**Issue by sweh** [coreui/coreui-free-react-admin-template#233]
When writing tests for views, I always get the above exception during import of coreui components.

I wrote a simple test for rendering of the dashboard component:

`src/views/dashboard/Dashboard.test.js`
```
import React from 'react';
import {shallow} from 'enzyme/build';
import Dashboard from './Dashboard';


it('mounts without crashing', () => {
  const wrapper = shallow(<Dashboard />);
  wrapper.unmount()
});
```

```
 ~/d/coreui-free-react-admin-template $ npm run test
 FAIL  src/views/dashboard/Dashboard.test.js
  ● Test suite failed to run

    /Users/sweh/dev/coreui-free-react-admin-template/node_modules/@coreui/utils/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import deepObjectsMerge from './deep-objects-merge'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@coreui/react/lib/fade/CFade.js:12:12)
```

Can you please provide a working test example for a view?

**Comment by woothu** [comment]
For hotfix, change import of `@coreui/utils/src` to `@coreui/utils` (import exist in charts imported on Dashboard)

**Comment by sweh** [comment]
Hi woothu,

after changing some of these imported you mentioned I am now stuck with a different error:

```  ● Test suite failed to run

    /Users/sweh/dev/coreui-free-react-admin-template/node_modules/@coreui/icons/js/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { freeSet } from './free/free-set.js'
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@coreui/react/lib/table/CDataTable.js:20:14)```

Also, those do not persist in any kind, so if I reinstall my project (e.g. when tests run on Jenkins), `coreui` is a fresh install from npm without these hotfixes. Am I missing something? How do you run tests against your frontends?

**Comment by woothu** [comment]
Another hotfix (tested on Dashboard)

in package.json `jest` section:
```
    "transformIgnorePatterns": [
      "node_modules/(?!(@coreui|tippy.js|perfect-scrollbar)/)"
    ]
```

We will probably fix it by default in the next `@coreui/react` minor release.

**Comment by sweh** [comment]
That worked, great!

Thanks a lot!!

**Comment by woothu** [comment]
From `3.1.0` version tests works without additional transpilation (you can delete `transformIgnorePatterns`)

**Comment by Tollwood** [comment]
I am using create react app without custom jest configuration
- create react app ->"react-scripts": "3.4.3",
- "jest": "24.9.0",
- "@coreui/react": "3.2.3"
but still get this error

`..../node_modules/@coreui/icons/js/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { freeSet } from './free/free-set.js' 
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { cilSpeedometer, cilCart, cilChartLine, cilCreditCard } from "@coreui/icons";`

Any ideas what I can do to fix it?

**Comment by woothu** [comment]
Check in "node_modules/coreui/coreui-react/package.json" the current version (it could not be the same as in your main package.json)

**Comment by NDTChan** [comment]
I'm getting this error too, plz help me:
- "react-scripts": "^4.0.3"
-  "@coreui/coreui": "4.0.1",
    "@coreui/icons": "^2.0.1",
    "@coreui/icons-react": "^2.0.0-rc.5",
    "@coreui/react": "4.0.0-rc.0",

 /Users/macbook/WebstormProjects/coreui-free-react-admin-template/node_modules/@coreui/icons/js/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { brandSet } from './brand/brand-set.js' 
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      22 | import { getStyle, hexToRgba } from '@coreui/utils'
      23 | import CIcon from '@coreui/icons-react'
    > 24 | import {
         | ^
      25 |   cibCcAmex,
      26 |   cibCcApplePay,
      27 |   cibCcMastercard,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/views/dashboard/Dashboard.js:24:1)
