### ISSUE TITLE
Trying to add an item in the sidebar navigation and the icon doesn't appear

### ISSUE THREAD

**Issue by jauggy** [coreui/coreui-free-react-admin-template#234]
I'm modifying the file in src>containers>_nav.js

I just tried adding the following item:
```
 {
    _tag: "CSidebarNavItem",
    name: "Video Conference",
    to: "/videoconference",
    icon: "cil-video"
  },
```

However, the icon doesn't show up. If I change to "cil-speedometer" it will show up. I believe that "cil-video" is part of the CoreUI Free icons. Is there something extra I need to do?

**Comment by woothu** [comment]
To use icon globally you have to first register it. Icons are registered in React.icons object (in src/index.js). You can import separate icons like in dashboard for smaller bundle size, or import whole set.
