### ISSUE TITLE
BrowserRouter not working with production build of v3

### ISSUE THREAD

**Issue by carlospence** [coreui/coreui-free-react-admin-template#236]
Anytime I change from HashRouter to BrowserRouter, there is always throws ChunkLoadError whenever you are navigating away from the dashboard. It took me several hours before I could drill it down to BrowserRouter because I was initially using connected-react-router which is using BrowserRouter beneath. 

You can easily replicate the error by changing HashRouter to BrowserRouter in the App.js and create a production build because it won't give any issue in development environment. The issue is always in the production environment. I first noticed it when I published to vercel without creating a local production build.

![image](https://user-images.githubusercontent.com/12647064/89153778-7fbd2b00-d55d-11ea-81c5-4ff18e2e5fe5.png)

**Comment by carlospence** [comment]
On further checking, the error pops up when dealing with child links such as theme, base, buttons, icons, notifications.

Links such as Charts, Users, Login, Pages (Register, Page404 and Page500) are working

**Comment by carlospence** [comment]
I changed the publicPath of webpack.config.js to publicPath: '/', and it worked. 

https://stackoverflow.com/questions/56576022/react-lazy-components-not-loaded-on-dynamic-routes.

Now, am working @using craco to change the webpack configuration information.

**Comment by carlospence** [comment]
I couldn't get the right way to use craco to set the publicPath. I tried the cold below using different combinations to no avail
```
module.exports = {
    webpack: {
        alias: {},
        plugins: [],
        output: {
            publicPath: '/',
        },
        configure: {  output: {
            publicPath: '/',
        },
         },
        configure: (webpackConfig, { env, paths }) => { return webpackConfig; }
    },
}
```
What I finally did is to follow this article and created my own react-scripts respository. [](https://auth0.com/blog/how-to-configure-create-react-app/)

I removed the existing react-scripts and add mine @carlospence/react-scripts. In my published react-scripts, I have already changed the publicPath to '/'.

It is working now but I believe a better solution can be applied. Will welcome any better way to resolve this issue.

**Comment by carlospence** [comment]
I noticed a side-effect today, on Child links that were giving issues earlier, anytime a refresh is done on such page, some assets are not fetched correctly from the right directory, The value of "PUBLIC_URL" changes. I had to remove reference to "Public_Url" in my index.html file.

**Comment by carlospence** [comment]
I started another project today and decided to look deeper into this issue and found a simple solution

[(https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing)]

By just adding the localhost path or url  (http://localhost:5000) sorted it out for running local build version. This is also applicable to the remotely hosted production build.

**Comment by Geometryse** [comment]
> By just adding the localhost path or url (http://localhost:5000) sorted it out for running local build version. This is also applicable to the remotely hosted production build.

where did you add the localhost path?

**Comment by MAfzalKhan1997** [comment]
same issue what should I do now ? any solution till now ?

**Comment by TPavlichek** [comment]
In package.json set "homepage": "/".

**Comment by MAfzalKhan1997** [comment]
> In package.json set "homepage": "/".

thanks @TPavlichek I came to this solution after lots of head scratching but then switched from core-ui as its free version is not maintained.

**Comment by yash-appwizards** [comment]
> In package.json set "homepage": "/".

Thanks @TPavlichek

**Comment by TammyAlok2** [comment]
In package.json set "homepage": "/".
Thanks  a bunch @TPavlichek  for your help
