### ISSUE TITLE
cDataTable pagination integrate API calls not showing data properly

### ISSUE THREAD

**Issue by ssomlk** [coreui/coreui-free-react-admin-template#237]
I am fetching users to my cDataTable from an API. Currently I have 12 users in the database. As shown below my current page is 1 and records per page is 10. This works fine.

![image](https://user-images.githubusercontent.com/30547921/89219840-2c46ed80-d5ee-11ea-9038-12f36ce1d74d.png)

But when i navigate to page 2 cDataTable shows no results. But according to the React developer tools I can see that I have 2 users fetched from the API.

![image](https://user-images.githubusercontent.com/30547921/89219891-408aea80-d5ee-11ea-9875-68401dab2e07.png)

Any ideas on how to solve this??

p.s: I have tried fetching users on page 1 after records per page changed to 25 and it gets me back my 12 users from the API

![image](https://user-images.githubusercontent.com/30547921/89219921-4ed90680-d5ee-11ea-9809-26537cf87f4d.png)

I tried using `<p></p>` tags to output users and it works fine, but not in cDataTable

![image](https://user-images.githubusercontent.com/30547921/89220318-fce4b080-d5ee-11ea-99cc-dbe99f27e68a.png)

**Comment by ssomlk** [comment]
@woothu Related to https://github.com/coreui/coreui-free-react-admin-template/issues/158. Any ideas??

**Comment by woothu** [comment]
in `CDataTable` - remove pagination props- `pagination`, `activePage`, `itemsPerPage` 

Below CDataTable create separate `CPagination` component, which will contain currently requested page

**Comment by ssomlk** [comment]
Works perfectly. Thanks @woothu
