### ISSUE TITLE
[Docs] Components props

### ISSUE THREAD

**Issue by kaueDM** [coreui/coreui-free-react-admin-template#239]
Would be nice to have a list of props inside each component documentation.

Sometimes i want to know what certain prop is but simply can't find anywhere. And the IDE doesn't help either:

<img width="750" alt="table" src="https://user-images.githubusercontent.com/20171863/89346407-5dbbc980-d67f-11ea-90f9-b309e44acfa8.png">

**Comment by woothu** [comment]
Documentation of components is available on https://coreui.io/react/docs/
