### ISSUE TITLE
CDataTable->itemsPerPageSelect reposition

### ISSUE THREAD

**Issue by michaeldino27** [coreui/coreui-free-react-admin-template#240]
Hello,

Just wanted to know if there is currently a setting where we can move the itemsPerPageSelect of the datatable somewhere like bottom|left or bottom|right cause currently its default to top|center.
I've been looking at the documentation and cant seem to find any solution to this.

Any help would do.

Thanks!
Michael D

**Comment by woothu** [comment]
Hi! the position is fixed, to change it you need create your own `itemsPerPageSelect` and place it in `underTableSlot`/`overTableSlot` prop

**Comment by alextaymx** [comment]
How to create our own itemsPerPageSelect ? is there any available props / slots ? it would be great if you could provide an example , thanks in advance
