### ISSUE TITLE
cil-boat-alt does not load

### ISSUE THREAD

**Issue by PabloCR** [coreui/coreui-free-react-admin-template#243]
I haven't gone through all the icons to see if this is affecting others but this one in particular I needed and found the issue.

I was trying to use this icon in the side nav bar and it throws a warning on the console:
**CIcon.js:14 Not existing icon: cilBoatAlt in React.icons object**

Steps to reproduce:

1. Download coreui-react package
2. Extract and npm install
3. npm start
4. Open src/containers/_nav.js
5. Replace any of the listed icon items with "cil-boat-alt"
6. Save and reload the page

- The icons is missing
- The previous console warning displayed
- Inspecting the element shows: "undefined" where the SVG data would be

**Comment by woothu** [comment]
As the warning states, you need to import icon to `React.icons` object to use it globally such as in https://github.com/coreui/coreui-free-react-admin-template/blob/master/src/index.js#L14

**Comment by PabloCR** [comment]
Thanks for the response, however I added the indicated lines and the issue persist. The icon does not load

Also could you please clarify why all other icons on the _nav.js work without needing to make changes to the default template and that icon in particular would need the extra lines?

Thanks

**Comment by woothu** [comment]
It is not about adding this line, it is about adding `cilBoatAlt` to icons object previously in https://github.com/coreui/coreui-free-react-admin-template/blob/master/src/assets/icons/index.js

**Comment by PabloCR** [comment]
Got it, that  fixed it.
Thanks for the support!
