### ISSUE TITLE
Page Redirection is not working in server

### ISSUE THREAD

**Issue by Imam-N** [coreui/coreui-free-react-admin-template#245]
In **App.js**  i am using the code below:

**<BrowserRouter forceRefresh={true}>**

Its Working in my system (Local System) - But not working in **AWS sandbox (static hosting)**

Otherwise I was removed the **forceRefresh={true}** - in my code 

Its Working on **AWS Sandbox** Also

But my page was Not Reloaded

**Comment by woothu** [comment]
It is not related to the template, but to `react-router`
