### ISSUE TITLE
Setting Icon in Nav Descriptor

### ISSUE THREAD

**Issue by einthecorgi2** [coreui/coreui-free-react-admin-template#246]
How can an .svg be used as an icon in the side bar nav when the nav is defined under the navConfig descriptor.

```js
export default {
  items: [
    {
      name: 'Page1',
      url: '/page1',
      icon: <img src={page1_logo}/>,
    },
]
```

Where `page1_logo` is an svg object

**Comment by woothu** [comment]
> nav is defined under the navConfig descriptor
 what do you mean by that?

**Comment by einthecorgi2** [comment]
When defining nav items by passing the json descriptor (as above) into `navConfig` for creating nav items. 

```js
sideBar = <AppSidebarNav navConfig={myPage} {...this.props} />;
```

**Comment by woothu** [comment]
You are probably using v2 of `@coreui/coreui-react`. Your issue is discussed in #220
