### ISSUE TITLE
Why I am always redirected to "/login#/dashboard" ?

### ISSUE THREAD

**Issue by Pabijonavicius** [coreui/coreui-free-react-admin-template#252]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/coreui/coreui-free-react-admin-template/issues?utf8=%E2%9C%93&q=is%3Aissue)
  **_I have looked solved issues, tried to apply suggested changes but it didn't help. 
  (Error: A React component suspended while rendering, but no fallback UI was specified. Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display. )_**
 
- The thing is when I started react app I am redirected to: **_localhost:3000/login#/dashboard_**
  I should be redirected to login page? Or at least this is what I want. I tried myself but couldn't achieve this...

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
   **_Windows 10_**
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera, Android Browser)
   **_Firefox 80.0 (64-bit)_**

**Comment by woothu** [comment]
This is not related to this template but to `react-router` configuration

**Comment by kalengbekas** [comment]
hi @ninode97 ,did you solve the issue ?
