### ISSUE TITLE
CDataTable: Table content doesn't support specifying the nested JSON in 'fields' props

### ISSUE THREAD

**Issue by hegdemohan** [coreui/coreui-free-react-admin-template#258]
The CDataTable displays undefined for the column where the "key" is specified in nested JSON.
ex: 

App.js:
```
export default function App() {
  const data = usersData;
  const fields = [{
      key: "name",
      label: "Name"
    },{
      key: "available.status",
      label: "Available"
    }];

   return (
<CDataTable
         items={data}
         fields={fields}
    />
  );
}
```

usersData.js:
```
export const usersData = [
  {
    id: 0,
    name: "John Doe",
    available: {
      status: false
    }
  },
  {
    id: 1,
    name: "Samppa Nori",
    available: {
      status: true
    }
  },
  {
    id: 2,
    name: "Estavan Lykos",
    available: {
      status: false
    }
  },
  {
    id: 3,
    name: "Chetan Mohamed",
    available: {
      status: true
    }
  }
];
```

The column for "Available" is undefined.

Below you can find the link for working demo of the issue

Operating system and version: Windows 10 Pro
Browser and version: All the browsers
Reduced test cases : [click here](https://codesandbox.io/s/ancient-sunset-ik3ht?file=/src/usersData.js:336-345)

**Comment by bystrewsky** [comment]
Maybe try to use scopedSlots: 
`   const scopedSlots = {'status':
      (item) => (
                    <td>
                        {item.available.status}
                    </td>
                  )
   }
`
In fields: 
`{
      key: "status",
      label: "Available"
    }`
And then 

`<CDataTable
         items={data}
         fields={fields}
         scopedSlots={scopedSlots}
    />`

**Comment by bystrewsky** [comment]
Maybe try to use scopedSlots:
```
const scopedSlots = {
      'status':
          (item) => ( 
            <td> {item.available.status} </td>
          ) 
      }
```
In fields:
``` 
const fields = [{
      key: "name",
      label: "Name"
    },{
      key: "status",
      label: "Available"
    }];
````
And then
```
<CDataTable 
  items={data} 
  fields={fields} 
  scopedSlots={scopedSlots} />
```
I don't feel like this is a good way to solve the problem, and it should work like in your example, but don't have another solution yet

**Comment by hegdemohan** [comment]
> Maybe try to use scopedSlots:
> 
> ```
> const scopedSlots = {
>       'status':
>           (item) => ( 
>             <td> {item.available.status} </td>
>           ) 
>       }
> ```
> 
> In fields:
> 
> ```
> const fields = [{
>       key: "name",
>       label: "Name"
>     },{
>       key: "status",
>       label: "Available"
>     }];
> ```
> 
> And then
> 
> ```
> <CDataTable 
>   items={data} 
>   fields={fields} 
>   scopedSlots={scopedSlots} />
> ```
> 
> I don't feel like this is a good way to solve the problem, and it should work like in your example, but don't have another solution yet

Thank you for your response :)

I would have used scoped slots if I was using the table in only one or two places, but I have created a common table component that is used by many other components in the application. So, to create scoped slots for displaying data from all those components will not be a good idea as it unnecessarily increases the size of the common table file as well as the readability of the code. So waiting for some help from Core UI team :D

**Comment by yathomasi** [comment]
cannot use filter/search with scoped slots, is there an alternative the column searchable ?

**Comment by shamvilkv** [comment]
@woothu Please help me with this issue

**Comment by Erumshammim** [comment]
> cannot use filter/search with scoped slots, is there an alternative the column searchable ?

have you found solution?
