### ISSUE TITLE
Unable to integrate new font Inter into coreui v3

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [coreui/coreui-free-react-admin-template#262]
Before opening an issue:

I am trying to use Inter font in my applications (https://github.com/philipbelesky/inter-ui#readme)

Tried all possible steps and override $font-family-base: "Inter";
But it is not working

**Comment by josephgodwinkimani** [comment]
In `src/scss/_custom.scss` do something like:

```
@font-face {
	font-family: 'Inter';
	font-style: normal;
	src: url('../assets/fonts/Inter.ttf');
}

:root {
  --cui-font-sans-serif: 'Inter';
}
```
