### ISSUE TITLE
CDataTable: unable to pass the props to table

### ISSUE THREAD

**Issue by ahtashamabbasse** [coreui/coreui-free-react-admin-template#263]
I tried to pass the id or className to CDataTable but noticed that not reflecting in browser. 

```
<CDataTable
              class="setting-table"
              id="setting-table"
             data-cy="setting-table"
              items={items}
              fields={[
                { key: 'key', label: t('Key') },
                { key: 'value', label: t('Value') }
              ]}
              striped
              clickableRows
              onRowClick={(row) => loadEditAttributeModal(row.key)}
            />

```

**Comment by yathomasi** [comment]
Please check react documentation as react component take class with className attribute and i don't think component take id as in html element unless you use the id prop and use that in JSX.
https://reactjs.org/docs/dom-elements.html
https://reactjs.org/docs/components-and-props.html

Did you check the documentation here https://coreui.io/react/docs/components/CDataTable

**Comment by ahtashamabbasse** [comment]
I'm aware about that,  but CDataTable takes class as `addTableClasses="setting-table"`

**Comment by nbpalomino** [comment]
I'm looking for Advanced-Table.js in CoreUI Free but i can't find it...  Where is ??
