### ISSUE TITLE
How can ı customize CDataTable -> itemsperpage

### ISSUE THREAD

**Issue by eraycankar** [coreui/coreui-free-react-admin-template#264]
![image](https://user-images.githubusercontent.com/56090358/95850046-e2e6ed00-0d58-11eb-8f54-5e2d9fd9d59c.png)
I want to change "items per page" to "customers per page"

**Comment by eraycankar** [comment]
ı just want to change  the text

**Comment by eraycankar** [comment]
thanks sir

**Comment by vutung3196** [comment]
hey @eraycankar , it seems like it doesn't work anymore?

**Comment by AiniMalik** [comment]
It is really helpful.

**Comment by tronganhnguyenthanh** [comment]
How can I customize itemsperpage from the bottom of datatable ?

**Comment by akshay2796** [comment]
How can I put the itemsPerPageSelect to bottom of CDataTable?
