### ISSUE TITLE
Side nav bar badge with dynamic counter

### ISSUE THREAD

**Issue by michaeldino27** [coreui/coreui-free-react-admin-template#270]
Hello,

Is there a way to append a badge on the minimized sidenavbar with a dynamic counter just like the image below.
![image](https://user-images.githubusercontent.com/48111530/98660777-a2db5000-2380-11eb-9a3d-cb37f22b15cf.png)
Obviously the number inside the badge will be constantly updated when new data is inserted. so i was hoping if there is a way to append the bade to the navItemIcon with a dynamic count inside a badge.

Thanks!
Mike

**Comment by Souvikray** [comment]
Hi, did you find a way to do this? I am into a similar situation where I want to add dynamic counter and also a dynamic submenu to a dropdown item based on API response. Let me know if did it.

**Comment by michaeldino27** [comment]
@Souvikray as you may know the coreui team did not respond to this issue/request yet so i went and improvised first, i just added a button inside the top-nav-bar that represents those menus with counter, our client accepted it so im good, now with regards to your dynamic submenu, i think you can use redux to store those menu globally then when you call the api you can trigger a reload to repopulate the submenu.
