### ISSUE TITLE
cannot use filter/search with scoped slots, is there an alternative the column searchable ?

### ISSUE THREAD

**Issue by shamvilkv** [coreui/coreui-free-react-admin-template#272]
cannot use filter/search with scoped slots, is there an alternative the column searchable ?

_Originally posted by @yathomasi in https://github.com/coreui/coreui-free-react-admin-template/issues/258#issuecomment-723953215_

**Comment by Erumshammim** [comment]
have you found any solution? I am also facing same issue.

**Comment by shamvilkv** [comment]
no,i didnt get any solution,you can load the data to state and set that data to table
