### ISSUE TITLE
Dynamic URLs in Sidebar

### ISSUE THREAD

**Issue by kisiledev** [coreui/coreui-free-react-admin-template#274]
I am using the CoreUI React Free Template to build out a React frontend project. The Sidebar component uses a navigation array of objects, which contains properties that are used to create CoreUI elements. Each object in the array has a "to" property, which provides the created nav item with a link, like so: 

```
const nav = [
{
    _tag: 'CSidebarNavItem',
    name: 'Account',
    to: '/user/:id/profile',
    icon: 'cil-user',
  }
]
```

The nav array is imported into a component and passed as a render prop to a CCreateElement component that in turn creates CSidebarNavItems, which are glorified React Router Links. 

**CCreateElement**
```
<CCreateElement
          items={navigation}
          {...props}
          components={{
            CSidebarNavDivider,
            CSidebarNavDropdown,
            CSidebarNavItem,
            CSidebarNavTitle
          }}
        />
```
I am trying to use dynamic urls in the "to" property, but my URLs return static strings ```/users/:id/profile```. How I can get these rendered elements to generate these dynamic URLs?

**Comment by kevinpranoto** [comment]
I have been trying to figure this out as well. Hoping to get some feedback from the coreui team.

**Comment by John-Oula** [comment]
Any solutions yet?

**Comment by kisiledev** [comment]
https://github.com/coreui/coreui-react/issues/165#issuecomment-845929990
