### ISSUE TITLE
how to prevent automatic collapse in AppSidebar

### ISSUE THREAD

**Issue by Gen0106** [coreui/coreui-free-react-admin-template#276]
Hello.
I am using @coreui/react 2.5.8 on Mac OS 10.14.5
In the app sidebar, when I click a children nav item, the previously selected nav parent is collapsed automatically.
I want to prevent this but no idea.
Please let me know how to do this.
Thank you in advance.

**Comment by xidedix** [comment]
@Gen0106 
with v2.5.8 this behaviour is based on `activeRoute` 
You can try to set sth like `url="/"` for sidebar nav-dropdown in _nav.js to avoid auto-close

**Comment by Gen0106** [comment]
Thanks for your support.
I set url for sidebar nav-dropdown so could avoid auto-close.
Very good.
But I have another problem.
When the application is started, all sidebar nav-dropdown is expanded.
To avoid this, how should I do?
I will be glad if you help me with this.
Thanks

**Comment by susannawcl1120** [comment]
I am using angular for development but also have the problem about all sidebar nav-dropdown expanded.

please follow the answer in this issue:
[https://github.com/coreui/coreui-free-angular-admin-template/issues/148](url)

It seems like the parent nav-item should add unique name of `url` in` _nav.js` file:
`{
  name: 'Parent',
  url: '/Parent', // please use a unique name for the url
  icon: 'icon-puzzle',
  children: [
    {
      name: 'Child Menu',
      url: '/url-to-child',
      icon: 'icon-flag'
    },
    {
      name: 'Another Child',
      url: '/url-to-another-child',
      icon: 'icon-bulb'
    }
  ],
  name: 'OtherParent',
  url: '/OtherParent', // please use a unique name for the url
  icon: 'icon-puzzle',
  children: [
    {
      name: 'Other one Child Menu',
      url: '/url-to-child',
      icon: 'icon-flag'
    },
    {
      name: 'Other two Another Child',
      url: '/url-to-another-child',
      icon: 'icon-bulb'
    }
  ],
}`

**Comment by PerryCodes** [comment]
I found the source of the problem with the AppSidebar on my 4K monitor scaled to 150% ... It had to do with a bad algorithm used to determine whether or not the sidebar was currently open or closed.  I reported my findings to Lukasz and he said that it was going to get fixed, but all products currently still exibit this problem.

**Comment by jesseagleboy** [comment]
@PerryCodes , I read your comment and I am feeling there is something along those lines. I can't seem to refactor my navigations into components or even use a Fragment without a CNavGroup collapsing automatically. I'm not sure if the algorithm also has an issue somehow with using Context. From testing the bare-minimum, if a CNavGroup and CNavItems are not all written explicitly under a CSidebar component, the auto-collapse will happen.
