### ISSUE TITLE
 am using node v15 and it requires node-sass 5.0.0, will you make this project node v15 compatible

### ISSUE THREAD

**Issue by q8tywolf** [coreui/coreui-free-react-admin-template#280]
I have updated my project to react 17 and updating my node version to 15v, but the only dependent package that needs updating is node-sass.

```
Failed to compile.

./src/scss/style.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/scss/style.scss)
Error: Node Sass version 5.0.0 is incompatible with ^4.0.0.
```

**Comment by cmatthey** [comment]
I am seeing a similar issue with v15.7.0 and node-sass ^4.14.1. Is there a solution or workaround? Thank you!

Failed to compile.

./src/scss/style.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/scss/style.scss)
Error: Node Sass does not yet support your current environment: Linux/musl 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
