### ISSUE TITLE
Wants to add multiple reducers in store but  after combining reducers sidebar reducer(already in template) is not working.

### ISSUE THREAD

**Issue by Erumshammim** [coreui/coreui-free-react-admin-template#288]
I am using coreui react admin template. In template there were only reducer for sidebar which were called by action dispatch in Header.js and Sidebar.js. In my project, I have created two more reducers and  which are combined and working but reducer function to toggle the sidebar is not working .. Below is the code .

![red](https://user-images.githubusercontent.com/37778174/108404988-5c7c7380-7242-11eb-8e0b-feb747b868b2.PNG)
![Capture](https://user-images.githubusercontent.com/37778174/108405146-8c2b7b80-7242-11eb-989f-d16387f03717.PNG)

**Comment by CSEKU160212** [comment]
How did you solve the issue? Thanks in advance!

**Comment by CSEKU160212** [comment]
How did you solve that?

**Comment by sahil-blulabs** [comment]
How did you solve that. @Erumshammim ..? I need to fix this too... and @CSEKU160212  did you find any workaround..?

**Comment by sahil-blulabs** [comment]
Okay, I just solved it.., its simple as 

I just needed to add this reducer to my list of reducers and thats all!!

```
const rootReducer = combineReducers({
  authReducer,
  usersReducer: usersReducerPersisted,
  eventsReducer: eventsReducerPersisted,
  buildingsReducer,
  pushnotifacationReducer,
  companiesReducer,
  announcementReducer,
  locationsReducer,
  reportsReducer,
  clustersReducer: clustersReducerPersisted,
  coreuiReducer,
})
```

**Comment by fajarfah7** [comment]
> Okay, I just solved it.., its simple as
> 
> I just needed to add this reducer to my list of reducers and thats all!!
> 
> ```
> const rootReducer = combineReducers({
>   authReducer,
>   buildingsReducer,
>   ... otherReducersHere,
>   coreui: coreuiReducer, // <<<<<<< This is my coreui reducer.
> })
> 
> 
> // and now I used the `useSelector` as
> 
> // file: AppSidebar.js
>   const unfoldable = useSelector((state) => state.coreui.sidebarUnfoldable)
>   const sidebarShow = useSelector((state) => state.coreui.sidebarShow)
> 
> // file: AppHeader.js
>   const sidebarShow = useSelector((state) => state.coreui.sidebarShow)
> ```

Thank you bro, you save my entire time to solve this, i working on this problem since last night, i still newbie on this
