### ISSUE TITLE
Localize the sidebar menu list

### ISSUE THREAD

**Issue by makkahwi** [coreui/coreui-free-react-admin-template#289]
Hi
I'm using i18next in my app for localization purpose. Do anyone know how could I use it to localize the menu items of the sidebar or coreui react?

**Comment by SamranTariq** [comment]
I'm using localization in core ui react using **"react-intl": "^5.10.16"**, By using this packge you can easily localize your project and yes the menu items of the sidebar also.
for detail visit [documentaion](https://formatjs.io/docs/getting-started/installation/).

### more info

when you create your locale files and ready to use them 

visit **coreui react** --> src --> container --> _nav.js
- import translations 
```
// Translation
import defaultMessage from "../translation/Messages";
import { FormattedMessage } from "react-intl";
```
then use your desired **FormattedMessage** tag, in your default export like ...

```
  {
    _tag: "CSidebarNavItem",
    name: (
      <FormattedMessage
        id="Dashboard"
        defaultMessage={defaultMessage.quote.Dashboard}
      />
    ),
    to: "/dashboard",
    icon: "cil-speedometer",
  },
```

**Comment by makkahwi** [comment]
Isn't there a way to use i18next? 
can't I in a way unpack the _nav list @ sidebar, add the i18next translation function and repack it?
