### ISSUE TITLE
Sidebar Minimizer doesn't adjust to height and hides available side menu items

### ISSUE THREAD

**Issue by jflayhart** [coreui/coreui-free-react-admin-template#29]
First off, even though this is a complaint, I really love this theme! It's saved me alot of time on the UI. 

The issue is minimizing the sidebar (not hide it) and shrinking the height of the browser viewport causes the minimize arrow to lose "responsiveness" to the point where it is no longer visible to restore the sidebar to its maximized state. Furthermore, under a certain height you cannot scroll to view other menu items (minimized state only).

This is quite disruptive because some mobile devices cannot function properly and delivers frustrating UX. I've tried looking into the cause but not entirely sure what's going on... running version 1.0.5 of CoreUI.

The expected behavior, at least for me, would be to have the minimize arrow ALWAYS on the bottom, and then the overflowY set to scroll, so you can still view all the nav items as you would in the maximized view.

Minimized:
<img width="452" alt="minimized" src="https://user-images.githubusercontent.com/6808172/32815961-2856343c-c97c-11e7-8bf1-5642334a17e1.png">

Shrink Browser Height (now minimizer icon is gone and have to make browser even taller than before to view minimize button):
<img width="311" alt="reduce_height-no-min-icon" src="https://user-images.githubusercontent.com/6808172/32815981-3a8b8c1a-c97c-11e7-91c8-93db888c54c6.png">

Cuts off other menu items, no scroll:
<img width="350" alt="reduce_height-cuttoff-menu-item-and-minimize-icon" src="https://user-images.githubusercontent.com/6808172/32815994-48133824-c97c-11e7-94e0-41ffa0268c7e.png">

**Comment by marchershey** [comment]
1. Open '_sidebar.scss'
2. Navigate to Line 79 - Should look like this:
```
.nav {
  @include sidebar-width($sidebar-borders, $sidebar-width);
  flex-direction: column;
  min-height: 100%;
}
```
3. Change ```min-height: 100%``` to ```min-height: calc(100% - 55px);```
4. Should look like this once done:
```
.nav {
  @include sidebar-width($sidebar-borders, $sidebar-width);
  flex-direction: column;
  min-height: calc(100% - 55px);
}
```

I had this same issue, so once I resolved it I thought it would be a good idea to help anyone else having the same issue. Hope it helped. If you have any questions, let me know.

**Comment by hirocsingh** [comment]
Actually that didn't work for me. If there is any other way ? @marchershey

**Comment by woothu** [comment]
This issue is fixed in v3 of the CoreUI
