### ISSUE TITLE
CForm onSubmit not working

### ISSUE THREAD

**Issue by andrewhamili** [coreui/coreui-free-react-admin-template#296]
Hi. I would like to ask how to use the CForm onSubmit event. I tried creating onSubmit but it does not work. Tried manually calling form.submit() on console, the form submits  but it does not call the function that I binded.

I would like to know if my usage of CForm with onSubmit event is correct or it is a bug.

Here is my fork impementing CForm with onSubmit event.

https://github.com/andrewhamili/coreui-free-react-admin-template/tree/issue/form-submit

**Comment by mghmay** [comment]
What is happening with this? I need to override the default behaviour of the enter button, I want to capture all of the data and redirect using the onSubmit prop
