### ISSUE TITLE
how to change side bar colour dark to white 

### ISSUE THREAD

**Issue by shekhawat777** [coreui/coreui-free-react-admin-template#299]
how to change sidebar colour from dark to white and  also hover colour on sidebar items

**Comment by universenl** [comment]
Asking my self this question also.

**Comment by mrholek** [comment]
@universenl set `colorScheme="light"`

**Comment by universenl** [comment]
@mrholek Getting the following when i add this to the sidebar: 
React does not recognize the `colorScheme` prop on a DOM element

**Comment by universenl** [comment]
Any update on this ?

**Comment by bloodykheeng** [comment]
hei did anyone get solution for this
