### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by the-jojo-jj** [coreui/coreui-free-react-admin-template#304]
trying at 8gb ram vps:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @babel/core@7.12.3
npm ERR! node_modules/@babel/core
npm ERR!   @babel/core@"7.12.3" from react-scripts@4.0.3
npm ERR!   node_modules/react-scripts
npm ERR!     dev react-scripts@"^4.0.3" from the root project
npm ERR!   @babel/core@"^7.12.3" from @svgr/webpack@5.5.0
npm ERR!   node_modules/@svgr/webpack
npm ERR!     @svgr/webpack@"5.5.0" from react-scripts@4.0.3
npm ERR!     node_modules/react-scripts
npm ERR!       dev react-scripts@"^4.0.3" from the root project
npm ERR!   9 more (babel-jest, babel-loader, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.13.12
npm ERR! node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm ERR!   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.13.12" from @babel/preset-env@7.14.2
npm ERR!   node_modules/@babel/preset-env
npm ERR!     @babel/preset-env@"^7.12.1" from @svgr/webpack@5.5.0
npm ERR!     node_modules/@svgr/webpack
npm ERR!       @svgr/webpack@"5.5.0" from react-scripts@4.0.3
npm ERR!       node_modules/react-scripts
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

and this is .npm/eresolve-report.txt:

# npm resolution error report

2021-05-26T01:13:18.282Z

Found: @babel/core@7.12.3
node_modules/@babel/core
  @babel/core@"7.12.3" from react-scripts@4.0.3
  node_modules/react-scripts
    dev react-scripts@"^4.0.3" from the root project
  @babel/core@"^7.12.3" from @svgr/webpack@5.5.0
  node_modules/@svgr/webpack
    @svgr/webpack@"5.5.0" from react-scripts@4.0.3
    node_modules/react-scripts
      dev react-scripts@"^4.0.3" from the root project
  peer @babel/core@"^7.0.0" from babel-jest@26.6.3
  node_modules/babel-jest
    babel-jest@"^26.6.0" from react-scripts@4.0.3
    node_modules/react-scripts
      dev react-scripts@"^4.0.3" from the root project
  peer @babel/core@"^7.0.0" from babel-loader@8.1.0
  node_modules/babel-loader
    babel-loader@"8.1.0" from react-scripts@4.0.3
    node_modules/react-scripts
      dev react-scripts@"^4.0.3" from the root project
  peer @babel/core@"^7.1.0" from babel-plugin-named-asset-import@0.3.7
  node_modules/babel-plugin-named-asset-import
    babel-plugin-named-asset-import@"^0.3.7" from react-scripts@4.0.3
    node_modules/react-scripts
      dev react-scripts@"^4.0.3" from the root project
  @babel/core@"7.12.3" from babel-preset-react-app@10.0.0
  node_modules/babel-preset-react-app
    babel-preset-react-app@"^10.0.0" from react-scripts@4.0.3
    node_modules/react-scripts
      dev react-scripts@"^4.0.3" from the root project
  peer @babel/core@"^7.0.0-0" from @babel/plugin-transform-react-constant-elements@7.13.13
  node_modules/@babel/plugin-transform-react-constant-elements
    @babel/plugin-transform-react-constant-elements@"^7.12.1" from @svgr/webpack@5.5.0
    node_modules/@svgr/webpack
      @svgr/webpack@"5.5.0" from react-scripts@4.0.3
      node_modules/react-scripts
        dev react-scripts@"^4.0.3" from the root project
  peer @babel/core@"^7.0.0-0" from @babel/preset-env@7.14.2
  node_modules/@babel/preset-env
    @babel/preset-env@"^7.12.1" from @svgr/webpack@5.5.0
    node_modules/@svgr/webpack
      @svgr/webpack@"5.5.0" from react-scripts@4.0.3
      node_modules/react-scripts
        dev react-scripts@"^4.0.3" from the root project
  peer @babel/core@"^7.0.0-0" from @babel/preset-react@7.13.13
  node_modules/@babel/preset-react
    @babel/preset-react@"^7.12.5" from @svgr/webpack@5.5.0
    node_modules/@svgr/webpack
      @svgr/webpack@"5.5.0" from react-scripts@4.0.3
      node_modules/react-scripts
        dev react-scripts@"^4.0.3" from the root project
  @babel/core@"^7.12.3" from @svgr/plugin-jsx@5.5.0
  node_modules/@svgr/plugin-jsx
    @svgr/plugin-jsx@"^5.5.0" from @svgr/webpack@5.5.0
    node_modules/@svgr/webpack
      @svgr/webpack@"5.5.0" from react-scripts@4.0.3
      node_modules/react-scripts
        dev react-scripts@"^4.0.3" from the root project
    @svgr/plugin-jsx@"^5.5.0" from @svgr/core@5.5.0
    node_modules/@svgr/core
      @svgr/core@"^5.5.0" from @svgr/webpack@5.5.0
      node_modules/@svgr/webpack
        @svgr/webpack@"5.5.0" from react-scripts@4.0.3
        node_modules/react-scripts
          dev react-scripts@"^4.0.3" from the root project
  peer @babel/core@"^7.0.0" from @babel/helper-compilation-targets@7.13.16
  node_modules/@babel/helper-compilation-targets
    @babel/helper-compilation-targets@"^7.13.16" from @babel/preset-env@7.14.2
    node_modules/@babel/preset-env
      @babel/preset-env@"^7.12.1" from @svgr/webpack@5.5.0
      node_modules/@svgr/webpack
        @svgr/webpack@"5.5.0" from react-scripts@4.0.3
        node_modules/react-scripts
          dev react-scripts@"^4.0.3" from the root project

Could not resolve dependency:
peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.13.12
node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
  @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.13.12" from @babel/preset-env@7.14.2
  node_modules/@babel/preset-env
    @babel/preset-env@"^7.12.1" from @svgr/webpack@5.5.0
    node_modules/@svgr/webpack
      @svgr/webpack@"5.5.0" from react-scripts@4.0.3
      node_modules/react-scripts
        dev react-scripts@"^4.0.3" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "@babel/core",
    "version": "7.12.3",
    "location": "node_modules/@babel/core",
    "dependents": [
      {
        "type": "prod",
        "name": "@babel/core",
        "spec": "7.12.3",
        "from": {
          "name": "react-scripts",
          "version": "4.0.3",
          "location": "node_modules/react-scripts",
          "dependents": [
            {
              "type": "dev",
              "name": "react-scripts",
              "spec": "^4.0.3",
              "from": {
                "location": "/root/aduaninstansi/my-project"
              }
            }
          ]
        }
      },
      {
        "type": "prod",
        "name": "@babel/core",
        "spec": "^7.12.3",
        "from": {
          "name": "@svgr/webpack",
          "version": "5.5.0",
          "location": "node_modules/@svgr/webpack",
          "dependents": [
            {
              "type": "prod",
              "name": "@svgr/webpack",
              "spec": "5.5.0",
              "from": {
                "name": "react-scripts",
                "version": "4.0.3",
                "location": "node_modules/react-scripts",
                "dependents": [
                  {
                    "type": "dev",
                    "name": "react-scripts",
                    "spec": "^4.0.3",
                    "from": {
                      "location": "/root/aduaninstansi/my-project"
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "@babel/core",
        "spec": "^7.0.0",
        "from": {
          "name": "babel-jest",
          "version": "26.6.3",
          "location": "node_modules/babel-jest",
          "dependents": [
            {
              "type": "prod",
              "name": "babel-jest",
              "spec": "^26.6.0",
              "from": {
                "name": "react-scripts",
                "version": "4.0.3",
                "location": "node_modules/react-scripts",
                "dependents": [
                  {
                    "type": "dev",
                    "name": "react-scripts",
                    "spec": "^4.0.3",
                    "from": {
                      "location": "/root/aduaninstansi/my-project"
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "@babel/core",
        "spec": "^7.0.0",
        "from": {
          "name": "babel-loader",
          "version": "8.1.0",
          "location": "node_modules/babel-loader",
          "dependents": [
            {
              "type": "prod",
              "name": "babel-loader",
              "spec": "8.1.0",
              "from": {
                "name": "react-scripts",
                "version": "4.0.3",
                "location": "node_modules/react-scripts",
                "dependents": [
                  {
                    "type": "dev",
                    "name": "react-scripts",
                    "spec": "^4.0.3",
                    "from": {
                      "location": "/root/aduaninstansi/my-project"
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "@babel/core",
        "spec": "^7.1.0",
        "from": {
          "name": "babel-plugin-named-asset-import",
          "version": "0.3.7",
          "location": "node_modules/babel-plugin-named-asset-import",
          "dependents": [
            {
              "type": "prod",
              "name": "babel-plugin-named-asset-import",
              "spec": "^0.3.7",
              "from": {
                "name": "react-scripts",
                "version": "4.0.3",
                "location": "node_modules/react-scripts",
                "dependents": [
                  {
                    "type": "dev",
                    "name": "react-scripts",
                    "spec": "^4.0.3",
                    "from": {
                      "location": "/root/aduaninstansi/my-project"
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "prod",
        "name": "@babel/core",
        "spec": "7.12.3",
        "from": {
          "name": "babel-preset-react-app",
          "version": "10.0.0",
          "location": "node_modules/babel-preset-react-app",
          "dependents": [
            {
              "type": "prod",
              "name": "babel-preset-react-app",
              "spec": "^10.0.0",
              "from": {
                "name": "react-scripts",
                "version": "4.0.3",
                "location": "node_modules/react-scripts",
                "dependents": [
                  {
                    "type": "dev",
                    "name": "react-scripts",
                    "spec": "^4.0.3",
                    "from": {
                      "location": "/root/aduaninstansi/my-project"
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "@babel/core",
        "spec": "^7.0.0-0",
        "from": {
          "name": "@babel/plugin-transform-react-constant-elements",
          "version": "7.13.13",
          "location": "node_modules/@babel/plugin-transform-react-constant-elements",
          "dependents": [
            {
              "type": "prod",
              "name": "@babel/plugin-transform-react-constant-elements",
              "spec": "^7.12.1",
              "from": {
                "name": "@svgr/webpack",
                "version": "5.5.0",
                "location": "node_modules/@svgr/webpack",
                "dependents": [
                  {
                    "type": "prod",
                    "name": "@svgr/webpack",
                    "spec": "5.5.0",
                    "from": {
                      "name": "react-scripts",
                      "version": "4.0.3",
                      "location": "node_modules/react-scripts",
                      "dependents": [
                        {
                          "type": "dev",
                          "name": "react-scripts",
                          "spec": "^4.0.3",
                          "from": {
                            "location": "/root/aduaninstansi/my-project"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "@babel/core",
        "spec": "^7.0.0-0",
        "from": {
          "name": "@babel/preset-env",
          "version": "7.14.2",
          "location": "node_modules/@babel/preset-env",
          "dependents": [
            {
              "type": "prod",
              "name": "@babel/preset-env",
              "spec": "^7.12.1",
              "from": {
                "name": "@svgr/webpack",
                "version": "5.5.0",
                "location": "node_modules/@svgr/webpack",
                "dependents": [
                  {
                    "type": "prod",
                    "name": "@svgr/webpack",
                    "spec": "5.5.0",
                    "from": {
                      "name": "react-scripts",
                      "version": "4.0.3",
                      "location": "node_modules/react-scripts",
                      "dependents": [
                        {
                          "type": "dev",
                          "name": "react-scripts",
                          "spec": "^4.0.3",
                          "from": {
                            "location": "/root/aduaninstansi/my-project"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "@babel/core",
        "spec": "^7.0.0-0",
        "from": {
          "name": "@babel/preset-react",
          "version": "7.13.13",
          "location": "node_modules/@babel/preset-react",
          "dependents": [
            {
              "type": "prod",
              "name": "@babel/preset-react",
              "spec": "^7.12.5",
              "from": {
                "name": "@svgr/webpack",
                "version": "5.5.0",
                "location": "node_modules/@svgr/webpack",
                "dependents": [
                  {
                    "type": "prod",
                    "name": "@svgr/webpack",
                    "spec": "5.5.0",
                    "from": {
                      "name": "react-scripts",
                      "version": "4.0.3",
                      "location": "node_modules/react-scripts",
                      "dependents": [
                        {
                          "type": "dev",
                          "name": "react-scripts",
                          "spec": "^4.0.3",
                          "from": {
                            "location": "/root/aduaninstansi/my-project"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "prod",
        "name": "@babel/core",
        "spec": "^7.12.3",
        "from": {
          "name": "@svgr/plugin-jsx",
          "version": "5.5.0",
          "location": "node_modules/@svgr/plugin-jsx",
          "dependents": [
            {
              "type": "prod",
              "name": "@svgr/plugin-jsx",
              "spec": "^5.5.0",
              "from": {
                "name": "@svgr/webpack",
                "version": "5.5.0",
                "location": "node_modules/@svgr/webpack",
                "dependents": [
                  {
                    "type": "prod",
                    "name": "@svgr/webpack",
                    "spec": "5.5.0",
                    "from": {
                      "name": "react-scripts",
                      "version": "4.0.3",
                      "location": "node_modules/react-scripts",
                      "dependents": [
                        {
                          "type": "dev",
                          "name": "react-scripts",
                          "spec": "^4.0.3",
                          "from": {
                            "location": "/root/aduaninstansi/my-project"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            },
            {
              "type": "prod",
              "name": "@svgr/plugin-jsx",
              "spec": "^5.5.0",
              "from": {
                "name": "@svgr/core",
                "version": "5.5.0",
                "location": "node_modules/@svgr/core",
                "dependents": [
                  {
                    "type": "prod",
                    "name": "@svgr/core",
                    "spec": "^5.5.0",
                    "from": {
                      "name": "@svgr/webpack",
                      "version": "5.5.0",
                      "location": "node_modules/@svgr/webpack",
                      "dependents": [
                        {
                          "type": "prod",
                          "name": "@svgr/webpack",
                          "spec": "5.5.0",
                          "from": {
                            "name": "react-scripts",
                            "version": "4.0.3",
                            "location": "node_modules/react-scripts",
                            "dependents": [
                              {
                                "type": "dev",
                                "name": "react-scripts",
                                "spec": "^4.0.3",
                                "from": {
                                  "location": "/root/aduaninstansi/my-project"
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "@babel/core",
        "spec": "^7.0.0",
        "from": {
          "name": "@babel/helper-compilation-targets",
          "version": "7.13.16",
          "location": "node_modules/@babel/helper-compilation-targets",
          "dependents": [
            {
              "type": "prod",
              "name": "@babel/helper-compilation-targets",
              "spec": "^7.13.16",
              "from": {
                "name": "@babel/preset-env",
                "version": "7.14.2",
                "location": "node_modules/@babel/preset-env",
                "dependents": [
                  {
                    "type": "prod",
                    "name": "@babel/preset-env",
                    "spec": "^7.12.1",
                    "from": {
                      "name": "@svgr/webpack",
                      "version": "5.5.0",
                      "location": "node_modules/@svgr/webpack",
                      "dependents": [
                        {
                          "type": "prod",
                          "name": "@svgr/webpack",
                          "spec": "5.5.0",
                          "from": {
                            "name": "react-scripts",
                            "version": "4.0.3",
                            "location": "node_modules/react-scripts",
                            "dependents": [
                              {
                                "type": "dev",
                                "name": "react-scripts",
                                "spec": "^4.0.3",
                                "from": {
                                  "location": "/root/aduaninstansi/my-project"
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "@babel/core",
    "spec": "^7.13.0",
    "error": "INVALID",
    "from": {
      "name": "@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining",
      "version": "7.13.12",
      "location": "node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining",
      "dependents": [
        {
          "type": "prod",
          "name": "@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining",
          "spec": "^7.13.12",
          "from": {
            "name": "@babel/preset-env",
            "version": "7.14.2",
            "location": "node_modules/@babel/preset-env",
            "dependents": [
              {
                "type": "prod",
                "name": "@babel/preset-env",
                "spec": "^7.12.1",
                "from": {
                  "name": "@svgr/webpack",
                  "version": "5.5.0",
                  "location": "node_modules/@svgr/webpack",
                  "dependents": [
                    {
                      "type": "prod",
                      "name": "@svgr/webpack",
                      "spec": "5.5.0",
                      "from": {
                        "name": "react-scripts",
                        "version": "4.0.3",
                        "location": "node_modules/react-scripts",
                        "dependents": [
                          {
                            "type": "dev",
                            "name": "react-scripts",
                            "spec": "^4.0.3",
                            "from": {
                              "location": "/root/aduaninstansi/my-project"
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}

**Comment by Habib-Netlinks** [comment]
try `npm install --force`

**Comment by hernandosalas** [comment]
Follow these steps to solve this issue –

Check if node_modules folder has write permission.
If react-scripts is not installed then install it within project scope –

`npm install react-scripts --save`

If above step doesn’t work then try removing node_modules folder and reinstall packages using this command –

`rm -rf node_modules && npm install`

You may also try auditing the packages for errors. It solves most of the problems –

`npm audit fix`

Sometimes packages got deprecated and updating them solves the problem –

`npm update`

Clearing the cache could help you too. Try this –

`npm cache clean --force && npm rebuild && npm install`
