### ISSUE TITLE
Attempted import error: 'CFormControl' is not exported from '@coreui/react'.

### ISSUE THREAD

**Issue by sunnydewangan** [coreui/coreui-free-react-admin-template#306]
I am using React CoreUI version ^3.2.2. When I am trying to use CFormControl it is throwing an exception saying "Attempted import error: 'CFormControl' is not exported from '@coreui/react'."

I can see it working in the example docs available on GitHub and Docs section, but in reality it is not working. Any idea?

**Comment by racsus** [comment]
Hi there, I have the same issue, any idea?

**Comment by nabilazora** [comment]
me too

**Comment by racsus** [comment]
I think it's because of the version, CFormControl is in React CoreUI version 4, not in version 3
