### ISSUE TITLE
Missing bootstrap folder 

### ISSUE THREAD

**Issue by thangchung** [coreui/coreui-free-react-admin-template#31]
I've seen like this project is missing the **bootstrap** folder inside **scss** folder. Because when using any sass tool for pre-processing styles, there are many undefined variables errors. I have seen that in the old repo, you have the bootstrap folder that declared a lot of these variables (https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/React_Full_Project/scss/bootstrap/). When I copied this folder into current project and import it in the _variables.scss, then it works correctly. Is it correct finding or you guys go with another approach? 
I do it at https://github.com/crm-core/crmcore/blob/master/src/hosts/CRMCore.ClientApp/src/styles/style.scss. If you guys are changing the approach, please let me know. Thank you very much.
@mrholek @tungphuong

**Comment by jefe-spain** [comment]
@thangchung Do you know the differences between React_Starter and React_Full ?

**Comment by thangchung** [comment]
@jefe-spain As far as I know, the React_Full have more pages than the React_Starter. You can see at https://github.com/mrholek/CoreUI-React/tree/master/React_Full_Project/src/views and https://github.com/mrholek/CoreUI-React/tree/master/React_Starter/src/views

**Comment by vndevil** [comment]
@thangchung :D Mình mới học nodejs và đang tìm hiểu bộ này, có nhiều chỗ chưa hiểu muốn hỏi, Chung chia sẻ kinh nghiệm được không?
