### ISSUE TITLE
Click CoreUI Logo on the top of the sidebar causes TypeError: target.className.includes is not a function

### ISSUE THREAD

**Issue by lukelu0520** [coreui/coreui-free-react-admin-template#310]
Dear coreui friends,

Simply click top-left logo of the sidebar, and below error shows up:

> TypeError: target.className.includes is not a function
HTMLDivElement.handleOnClick
src/components/sidebar/CSidebar.tsx:128
  125 | 
  126 | const handleOnClick = (event: Event) => {
  127 |   const target = event.target as HTMLAnchorElement
> 128 |   target &&
      | ^  129 |     target.className.includes('nav-link') &&
  130 |     !target.className.includes('nav-group-toggle') &&
  131 |     mobile &&

Comment out  line#37 of AppSidebar.js can suppress the error.

We are using Ubuntu 18.04, Chrome Version 90.0.4430.93 (Official Build) (64-bit).

Hope to hear your expertise.

Best,
--Luke

**Comment by jagtarsinghwork** [comment]
Same issue with me
