### ISSUE TITLE
TypeError: target.className.includes is not a function

### ISSUE THREAD

**Issue by jagtarsinghwork** [coreui/coreui-free-react-admin-template#314]
When we click on Sidebar icon in core 4.0  admin template it will give this error

kindly describe me How can i fix this issue

TypeError: target.className.includes is not a function
handleOnClick
C:/Users/jagta/OneDrive/Documents/BRSOFTECH/USA JOBS/src/components/sidebar/CSidebar.tsx:128

  125 | 
  126 | const handleOnClick = (event: Event) => {
  127 |   const target = event.target as HTMLAnchorElement
> 128 |   target &&
      | ^  129 |     target.className.includes('nav-link') &&
  130 |     !target.className.includes('nav-group-toggle') &&
  131 |     mobile &&

Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/coreui/coreui-free-react-admin-template/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs

When asking general "how to" questions:

- Please do not open an issue here

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to CoreUI Admin Template
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by theavazov** [comment]
this error shows, coz there is no class in your targeted element, when you click something svg which was wrapper by div and you write logic to wrapper div, but when you click you still targeted svg, and svg has no class, every class logic was in div wrapper
