### ISSUE TITLE
Dynamic route doesn't work in 4.0

### ISSUE THREAD

**Issue by tomriddle7** [coreui/coreui-free-react-admin-template#315]
routes.js
```
const routes = [
  { path: "/", exact: true, name: "Home" },
  { path: "/product/list", name: "ProductList", component: ProductList },
  { path: "/product/detail/:id", name: "ProductDetail", component: ProductDetail }
];
```

when I enter /product/detail/2, It throws **Uncaught TypeError: Cannot read property 'name' of undefined**.

AppGreadcrumb.js
```
const getRouteName = (pathname, routes) => {
    const currentRoute = routes.find((route) => route.path === pathname);
    return currentRoute.name;
  };
```

I guess that '/product/detail/:id' is not same as '/product/detail/2, so currentRoute return undefined and getRouteName function throw error.

Thanks.

**Comment by manprajapat** [comment]
yes, me also facing this issue.

**Comment by nicolerenee** [comment]
I was able to fix this by changing the `getRouteName` to:

```
const getRouteName = (pathname, routes) => {
    const currentRoute = routes.find(
      (route) =>
        matchPath(pathname, {
          path: route.path,
          exact: route.exact,
          strict: route.strict,
        }) != null,
    )
    return currentRoute.name
  }
```

You will also need to add the following import:
```
import { matchPath } from 'react-router'
```

**Comment by huyentrangle** [comment]
I fixed it like you but it still doesn't work and gives an error **Uncaught TypeError: Cannot read property 'name' of undefined.**
What should I do?

**Comment by huyentrangle** [comment]
> I was able to fix this by changing the `getRouteName` to:
> 
> ```
> const getRouteName = (pathname, routes) => {
>     const currentRoute = routes.find(
>       (route) =>
>         matchPath(pathname, {
>           path: route.path,
>           exact: route.exact,
>           strict: route.strict,
>         }) != null,
>     )
>     return currentRoute.name
>   }
> ```
> 
> You will also need to add the following import:
> 
> ```
> import { matchPath } from 'react-router'
> ```

I fixed it like you but it still doesn't work and gives an error Uncaught TypeError: Cannot read property 'name' of undefined.
What should I do?

**Comment by mriege** [comment]
@huyentrangle I have the same problem. Did you found a solution?

**Comment by miguelfep** [comment]
I can solve the problem by putting one more item on the routes without the parameter
for example:

**Comment by miguelfep** [comment]
> @huyentrangle I have the same problem. Did you found a solution?

I can solve the problem by putting one more item on the routes without the parameter
for example:
const routes = [
{ path: "/", exact: true, name: "Home" },
{ path: "/product/list", name: "ProductList", component: ProductList },
{ path: "/product/detail/", name: "Detail", component: ProductDetail }
{ path: "/product/detail/:id", name: "ProductDetail", component: ProductDetail }
];

**Comment by mrholek** [comment]
Fixed in 4.2.0

**Comment by Prasaa84** [comment]
> > @huyentrangle I have the same problem. Did you found a solution?
> 
> I can solve the problem by putting one more item on the routes without the parameter for example:
> 
> ```
> const routes = [
>     { path: "/", exact: true, name: "Home" },
>     { path: "/product/list", name: "ProductList", component: ProductList },
>     { path: "/product/detail/", name: "Detail", component: ProductDetail }
>     { path: "/product/detail/:id", name: "ProductDetail", component: ProductDetail }
>   ];
> ```

Hi.. how to make this in react 18. This code is not working on it. It says router.ts:11 No routes matched location "/admin/profile"  in console.

**Comment by Prasaa84** [comment]
Hi.. how to make this in react 18. This code is not working on it. Browser console says ' No routes matched location "/admin/sometexthere" '
