### ISSUE TITLE
CDataTable missing in core ui 4

### ISSUE THREAD

**Issue by ahtashamabbasse** [coreui/coreui-free-react-admin-template#317]
Missing CDataTable component. 

What's your plan for CDataTable component in Core UI 4?

**Comment by Israa53** [comment]
unsubscribe
________________________________
From: Ahtasham Abbas ***@***.***>
Sent: Monday, July 26, 2021 10:29 PM
To: coreui/coreui-free-react-admin-template ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [coreui/coreui-free-react-admin-template] CDataTable missing in core ui 4 (#317)


What's your plan for CDataTable component in Core UI 4?

**Comment by amplexus** [comment]
I'm interested in this too. It seems coreui has renamed the v3.4 cdatatable to csmarttable in v4, and decided to make it part of the charged feature set.

Given your main competitor -  materialui - has a similar feature that is free, I think that is a somewhat shortsighted move. 

It also makes developers reluctant to commit to the product if features that are free in one version become charged in the updated version. What other free features will become charged in the next patch?

**Comment by mrholek** [comment]
@amplexus regarding materialui please check this - https://mui.com/components/data-grid/#mit-vs-commercial

We're going to add a lite version of SmartTables in the free version.
