### ISSUE TITLE
./src/_nav.js Attempted import error: 'cilrouter' is not exported from '@coreui/icons'.

### ISSUE THREAD

**Issue by kanghan90** [coreui/coreui-free-react-admin-template#326]
- Operating system: ubuntu 20
- Browser and version : firefox 
- Core UI version: v4.0.0-beta.1

Can not export existing icons.
./src/_nav.js Attempted import error: 'cilrouter' is not exported from '@coreui/icons'.

**Comment by mrholek** [comment]
Try `cilRouter` instead of `cilrouter`
