### ISSUE TITLE
ParserError when running npm build on fresh repo

### ISSUE THREAD

**Issue by StackTraceYo** [coreui/coreui-free-react-admin-template#327]
I pulled down the repo, and was trying to run the production build

`~/coreui-free-react-admin-template$ npm run build

> @coreui/coreui-free-react-admin-template@4.0.0-rc.2 build /home/axf29/coreui-free-react-admin-template
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/scss/style.scss
ParserError: Syntax Error at line: 1, column 26
`

It runs fine in dev mode.

**Comment by ajzpiv97** [comment]
I am also getting the same error when try to run yarn build.

$ yarn build
yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/scss/style.scss
ParserError: Syntax Error at line: 1, column 26


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mrholek** [comment]
It's problem with react-scripts and cssnano, we're working on it.

**Comment by mrholek** [comment]
@StackTraceYo @ajzpiv97 Fixed

**Comment by sintha-dwiferma** [comment]
Dear @mrholek we're having the same issue on  react-scripts build, please look at the issue #373
