### ISSUE TITLE
property 'visible' CNavGroup not work as expert after upgrade to v4.0.0-rc.3

### ISSUE THREAD

**Issue by binhvoq** [coreui/coreui-free-react-admin-template#328]
It look like that 'visible' property do not take any effects in CNavGroup (v4.0.0-rc.3)

`        <CNavGroup visible toggler="Nav dropdown">`
              `<CNavItem href="#">Nav dropdown item</CNavItem>`
          `<CNavItem href="#">Nav dropdown item</CNavItem>`
      `  </CNavGroup>`
-  When I run this code in v4.0.0-beta.0, the CNavGroup will remains open when refresh page or click another NavItem in that group.
-  When I run this code in v4.0.0-rc.3, the CNavGroup will close when refresh page or click another NavItem in that group. 

Operating system and version: Window 10
Browser and version: Chrome

**Comment by universenl** [comment]
Having this issue as well on 4.4.0, seems that the variable set to true fixed aint opening the navgroup.

**Comment by AhmedMaqbool** [comment]
Having the same issue anybody found a fix ?
