### ISSUE TITLE
Data table removed from v4

### ISSUE THREAD

**Issue by zorox-1** [coreui/coreui-free-react-admin-template#332]
is data table removed from the free version 4?

**Comment by hespinola** [comment]
Looks like it was moved to a new SmartTable component for the Pro version

https://coreui.io/react/docs/4.0/components/smart-table/

**Comment by ahmadazizi** [comment]
I've used `CDataTable` across my project in V3.
I'm migrating to V4(almost done) and I see this component is totally removed. 
It's not a good/fair decision, there wasn't anything in the documentation that this is gone without any alternatives! What should I do right now???

**Comment by zorox-1** [comment]
stay on v3 dude.. the free version of v4 is very basic

**Comment by ahmadazizi** [comment]
The best solution for me was to migrate the missing `CDataTable` component from v3 . It required modifying some bootstrap class names.
