### ISSUE TITLE
jsconfig.json error:  node_modules/agent-base/dist/src/index notfound on coreui template v4 ?

### ISSUE THREAD

**Issue by amirfaisalz** [coreui/coreui-free-react-admin-template#333]
I have a warning in jsconfig.json that node_modules/agent-base/dist/src/index is not found.

This is my jsconfig.json 

{
  "compilerOptions": {
    "baseUrl": "."
  },
  "include": ["src"]
}

My Operating system and version (Ubuntu Ubuntu 20.04.3 LTS).

Please help how to solve this warning.

![coreui](https://user-images.githubusercontent.com/60026193/139023676-3b7b30cf-9364-45cb-ab3f-f3380e33cae2.png)

**Comment by yanickrochon** [comment]
This not only restricted to this project. I also have this error, and my project isn't using CoreUI

**Comment by allamgr** [comment]
Disabling typescript in the workspace options seems to be the one thing that stopped this warning for me:

```"typescript.validate.enable": false,```

But I don't want to disable the typescript validation, if you found other solution just let me know!
