### ISSUE TITLE
Chart reference for @coreui/react-chartjs (useRef returns undefined)

### ISSUE THREAD

**Issue by tamojay-dey** [coreui/coreui-free-react-admin-template#335]
I have tried to capture the reference of a react chart but it returns undefined. 
`<CCardBody>
      <CChart
          ref={chartRef}
          id="react-chart"
          type="line"
          datasets={finaldata} 
          options={options} 
          labels={Xaxis} 
      />
  </CCardBody>`

and defining chartRef as:
`const chartRef = useRef()`

I thought it could be because of the fact that it lacks react-chartjs-2 dependency as told [here](https://github.com/reactchartjs/react-chartjs-2/issues/464). but it is still returning undefined. I am using Core UI 3.2. Any suggestion how to get the reference? I need the chart reference to save it to a base64image.

**Comment by Morrious** [comment]
Same issue here. I don't think they gave us access to the chart ref, maybe they did in newer versions of CoreUI, but I am also on 3.2. I will probably just extend the CChart component and override their ref.
