### ISSUE TITLE
C:\Program Files\nodejs\node.exe: bad option: --openssl-legacy-provider

### ISSUE THREAD

**Issue by qifeng32** [coreui/coreui-free-react-admin-template#336]
![error](https://user-images.githubusercontent.com/42432970/144192789-82d2d203-4879-461d-9014-d2ba26463e66.jpg)
This error appeared when I tried to npm start after npm install the coreui-free-react-admin-template. Does anyone know how to fix this issue?

**Comment by game5413** [comment]
Due to changes on [Node.js v12](https://nodejs.org/en/blog/release/v17.0.0/), `--openssl-legacy-provider` was added for handling key size on OpenSSL v3. For now i do workaround with this options.

1. rearrange parameter position like
```json
"scripts": {
    "build": "react-scripts build --openssl-legacy-provider",
    "start": "react-scripts start --openssl-legacy-provider",
    ...rest scripts that already provided
}
```

2. add NODE_OPTIONS flag from CLI or .env file
```env
NODE_OPTIONS="--openssl-legacy-provider"
```

Another options provider on this [reference](https://www.reddit.com/r/webdev/comments/qd14bm/comment/hhje1dr/?utm_source=share&utm_medium=web2x&context=3). CMIWW

**Comment by qifeng32** [comment]
> 
Hmmmm. I am using v16.13.0 for my nodejs though.

**Comment by game5413** [comment]
You can try option 1 or 2 that i provided (or remove `--openssl-legacy-provider` if still recognized bad option after try previous options), the problem is that parameter that author passed was for Node.js 17 not recognized by node version below 17.

**Comment by qifeng32** [comment]
> You can try option 1 or 2 that i provided (or remove `--openssl-legacy-provider` if still recognized bad option after try previous options), the problem is that parameter that author passed was for Node.js 17 not recognized by node version below 17.

Seems to be working now. Thank you so much!

**Comment by AxelPariss** [comment]
Yep ! Thank you @game5413 
I run this command to update my node version (from 16 to 17) : 
```
nvm install node --reinstall-packages-from=node
```
And that's work :)

**Comment by mrholek** [comment]
I removed `--openssl-legacy-provider` from `start` and `build` scripts and added dedicated scripts for Node 17+ `start:n17` and `build:n17`

**Comment by Sallar-Khan** [comment]
"scripts": {
    "start": "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts build",
  }
//ADD this in your script tag instead above one
"scripts": {
    "build": "react-scripts build --openssl-legacy-provider",
    "start": "react-scripts start --openssl-legacy-provider",
}

**Comment by singhhp** [comment]
Run - npm install node --reinstall-packages-from=node
and Rearrange 
"scripts": {
    "build": "react-scripts  --openssl-legacy-provider build ",
    "start": "react-scripts  --openssl-legacy-provider start",
    ...rest scripts that already provided
}
to 
"scripts": {
    "build": "react-scripts build --openssl-legacy-provider",
    "start": "react-scripts start --openssl-legacy-provider",
    ...rest scripts that already provided
}

**Comment by joefelx** [comment]
> 
Hey guys this one worked for me👇
`npm install node --reinstall-packages-from=node`

**Comment by Queen-Geek** [comment]
![image](https://github.com/user-attachments/assets/914b70a7-21d6-4699-9bd0-adb457bed728)
Attempting to run ng build --prod --base-href to onboard this application to AWS, but I'm getting the error above. Is anyone aware of the cause?
