### ISSUE TITLE
I have 1 problem using your theme

### ISSUE THREAD

**Issue by huyentrangle** [coreui/coreui-free-react-admin-template#338]
in Router file
{ path: "/edit-user/:id", name: "AddUser", component: EditUser },

end my code : <Link   to={{pathname: `/edit-user/${record.id}`,state: { ...record } }}     >  Edit</Link>
I can't get param and pathname URL end show bug "Cannot read properties of undefined (reading 'name')" in file /components/AppBreadcrumb.js:13
Can you show me why this is so?

**Comment by mrholek** [comment]
I will fix it next release

**Comment by lbz-life** [comment]
@mrholek thank you for looking into this, do you have an idea when the new release will be released?
