### ISSUE TITLE
CoreUi packages errror for react 17 - cannot install packages

### ISSUE THREAD

**Issue by faizan-karigar** [coreui/coreui-free-react-admin-template#342]
hile resolving: @coreui/coreui-pro-react-admin-template@3.2.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.1" from react-big-calendar@0.30.0
npm ERR! node_modules/react-big-calendar
npm ERR!   react-big-calendar@"^0.30.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Faizan\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Faizan\AppData\Local\npm-cache\_logs\2021-12-17T12_49_47_585Z-debug.log

**Comment by mrholek** [comment]
Please try `npm install --force` od `yarn install`

**Comment by faizan-karigar** [comment]
> Please try `npm install --force` od `yarn install`

error C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Faizan\\Karigar\\Germany\\Shopware\\_frontend\\coreui\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.13.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Faizan\AppData\Local\Programs\Python\Python37-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Faizan\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Faizan\\Karigar\\Germany\\Shopware\\_frontend\\coreui\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Faizan\Karigar\Germany\Shopware\_frontend\coreui\node_modules\node-sass
gyp ERR! node -v v16.13.1


yarn install is give this error and npm install --force also didn't work

**Comment by mrholek** [comment]
Please replace `node-sass` with `sass`.

BTW. We fixed all issues in version 3.2.1, id you have a valid license you can download it here https://coreui.io/download/

**Comment by faizan-karigar** [comment]
yarn install and with sass worked
