### ISSUE TITLE
Lots of warnings during npm start

### ISSUE THREAD

**Issue by shuchow** [coreui/coreui-free-react-admin-template#343]
Hi, I cloned this repo and running the directory as a Docker volume in the official node16 image.

Per instructions, I ran npm install (in the container) and it worked fine.  node_modules was installed, and package-lock.json was created.

However, on npm start, I get a lot of warnings such as this:

`
WARNING in ./node_modules/@coreui/react/dist/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/usr/app/node_modules/@coreui/react/packages/coreui-react/src/components/toast/CToastHeader.tsx' file: Error: ENOENT: no such file or directory, open '/usr/app/node_modules/@coreui/react/packages/coreui-react/src/components/toast/CToastHeader.tsx'
 @ ./src/views/pages/page500/Page500.js 5:0-106 13:35-45 14:37-41 16:39-43 46:41-52 48:44-59 60:43-53 67:43-50
 @ ./src/App.js 34:52-91
 @ ./src/index.js 134:0-24 141:33-36

WARNING in ./node_modules/@coreui/react/dist/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/usr/app/node_modules/@coreui/react/packages/coreui-react/src/components/toast/CToaster.tsx' file: Error: ENOENT: no such file or directory, open '/usr/app/node_modules/@coreui/react/packages/coreui-react/src/components/toast/CToaster.tsx'
 @ ./src/views/pages/page500/Page500.js 5:0-106 13:35-45 14:37-41 16:39-43 46:41-52 48:44-59 60:43-53 67:43-50
 @ ./src/App.js 34:52-91
 @ ./src/index.js 134:0-24 141:33-36

WARNING in ./node_modules/@coreui/react/dist/index.es.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/usr/app/node_modules/@coreui/react/packages/coreui-react/src/components/tooltip/CTooltip.tsx' file: Error: ENOENT: no such file or directory, open '/usr/app/node_modules/@coreui/react/packages/coreui-react/src/components/tooltip/CTooltip.tsx'
 @ ./src/views/pages/page500/Page500.js 5:0-106 13:35-45 14:37-41 16:39-43 46:41-52 48:44-59 60:43-53 67:43-50
 @ ./src/App.js 34:52-91
 @ ./src/index.js 134:0-24 141:33-36
`

The issue seems to be that it's looking for '/usr/app/node_modules/@coreui/react/packages/*', but the packages directory does not exist.  /usr/app/node_modules/@coreui/react has this:

`root@0b0c9ea79f6a:/usr/app/node_modules/@coreui/react# ls -la
total 16

drwxr-xr-x 7 root root  224 Jan  1 03:30 .

drwxr-xr-x 9 root root  288 Jan  1 03:30 ..

-rw-r--r-- 1 root root 1086 Jan  1 03:30 LICENSE

-rw-r--r-- 1 root root 5637 Jan  1 03:30 README.md

drwxr-xr-x 9 root root  288 Jan  1 03:31 dist

-rw-r--r-- 1 root root 1583 Jan  1 03:30 package.json

drwxr-xr-x 5 root root  160 Jan  1 03:31 src`

It doesn't seem to affect the Dashboard demo, but I'm curious if there's a way to fix these issues.  Thanks.

**Comment by mrholek** [comment]
We have a bug in rollup so we generate the wrong paths in source maps, we fixed it in previous releases.
