### ISSUE TITLE
Iframe appear after auto reload browser.

### ISSUE THREAD

**Issue by kiditran** [coreui/coreui-free-react-admin-template#344]
My information:

- OS: Window10
- Browser: Chrome & Firefox
- CoreUI React: v4.1.1
- Node: v14.18.0
- NPM: 6.14.15

Hi CoreUI React Team, 

Today, I pull v4.1.1 from Github to my PC. Everything works fine but I don't understand that each time I change code, an iframe appears when the browser automatically loading. It contains all Coreui document tags that are really weird.

So you can see this screenshot and support me soon
![image](https://user-images.githubusercontent.com/24970265/148303035-1c829130-c686-4b13-80a2-130aab11b9e7.png)

Thank you so much.
Kidi.

**Comment by babila88** [comment]
i Have same problem

**Comment by thisiskhandev** [comment]
Same getting issues
