### ISSUE TITLE
Cant set 404 Page to Redirect to 404 page with BrowserRouter

### ISSUE THREAD

**Issue by rakshitbharat** [coreui/coreui-free-react-admin-template#345]
- I want to set page 404 or redirect to 404 with BrowserRouter but its not working can giving error
- BTW all routes working fine which are defined just 404 not working

![image](https://user-images.githubusercontent.com/17176729/148750444-6e1f12ec-dfbb-4d6d-a73f-a2b1a3094945.png)
![image](https://user-images.githubusercontent.com/17176729/148750493-b10c4258-2a4a-4d04-8f47-a85fa0628827.png)

**Comment by mrholek** [comment]
Do you use the latest version v4.2.0 ?
