### ISSUE TITLE
npm run build	"Failed to compile."

### ISSUE THREAD

**Issue by manishoctal** [coreui/coreui-free-react-admin-template#373]
I have attached the logs,
while creating a production build, it throws me an error. 

[chum-admin.df4d9596-0969-4065-8063-8698a68a86e4.log](https://github.com/coreui/coreui-free-react-admin-template/files/8283732/chum-admin.df4d9596-0969-4065-8063-8698a68a86e4.log)
 
![image](https://user-images.githubusercontent.com/43563293/158787204-3514a21c-9b67-4dd3-ad6d-0475b7ba3535.png)

**Comment by Alejandro151148** [comment]
tengo el mismo error, se logro resolver de alguna manera?

**Comment by luizcsbh** [comment]
Hello everyone, I had a similar problem and to solve it I had to do some things like update my Node.js version to 16.14.2 create a webpack file and add two libraries
```javascript
{
    test: /\.(scss)$/,
    use: [{
      loader: 'style-loader', // inject CSS to page
    }, {
      loader: 'css-loader', // translates CSS into CommonJS modules
    }, {
      loader: 'postcss-loader', // Run post css actions
      options: {
        plugins: function () { // post css plugins, can be exported to postcss.config.js
          return [
            require('precss'),
            require('autoprefixer')
          ];
        }
      }
    }, {
      loader: 'sass-loader' // compiles Sass to CSS
    }]
  }
```
```node
 npm install --save-dev prettier
```
and in my package.json file insert the library
```json
"resolutions": {
    "react-scripts/postcss-preset-env/postcss-custom-properties": "^10.0.0"
  },
```
and finally

```node
 npm install
```

**Comment by thnardi** [comment]
Hi @luizcsbh i'm having the same issue here and cannot figure out your answare, especially the code snippet above you referenced webpack. 

I have no experience with webpack at all and since the template in question already has his own integration and context it gets even more complicated. 

Could you provide a more complete answer, showing the full code of the webpack file, where you put it on project and any context you find necessary. 

thank you very much!

**Comment by manishoctal** [comment]
It is still showing an error. @thnardi Can you explain more?

**Comment by manprajapat** [comment]
I fixed it by doing a good hack.

_src\scss\_variables.scss_

`$enable-grid-classes: false !default;`

**Comment by joefelx** [comment]
Try this! Sometimes linting causes issues.
Add these code in `next.config.js`

``` 
module.exports = {
  eslint: {
    ignoreDuringBuilds: true,
  },
}
```

**Comment by Okly2023** [comment]
Hello everybody. Hope you are doing well . anyone can help me! i have the issue too. npm run build error
these is the code given after press enter:

PS C:\SocialApp\social-app> npm run build

social-app@0.1.0 build
react-scripts build

Creating an optimized production build...
Failed to compile.

Error: Parse Error: <meta Content-Security-Policy-Report-Only
: script-src




<title>React App</title>
<script defer src="/static/js/main.d4cc64a6.js"></script></h ead>

You need to enable JavaScript to run this app.< /noscript>

<!--
This HTML file is a template.
If you open it directly in the browser, you will see an empty page.
    You can add webfonts, meta tags, or analytics to this f  ile.
    The build step will place the bundled scripts into the 
tag.
