### ISSUE TITLE
Sidebar not setting active

### ISSUE THREAD

**Issue by diegogangl** [coreui/coreui-free-react-admin-template#380]
- Operating system and version: Fedora Linux 35
- Browser and version: Brave [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/)

I can't get the sidebar to mark navitems as active once I click on them. This should be automatic right? Or is there some prop I need to set somehow?

```
            <CSidebarNav>
                <CNavItem href="/">
                    <CIcon customClassName="nav-icon" icon={cilSpeedometer} />
                    Inicio
                </CNavItem>
                <CNavItem href="/events">
                    <CIcon customClassName="nav-icon" icon={cilListRich} />
                    Eventos
                </CNavItem>
            </CSidebarNav>
```

**Comment by maksumon** [comment]
> 

You need to use `active` props in the `CNavItem` component.
