### ISSUE TITLE
Unable to upload changed project into a personal reposatory 

### ISSUE THREAD

**Issue by Zainab-Fahim** [coreui/coreui-free-react-admin-template#382]
I'm getting the following error while I'm trying to push the changes of the dashboard into a personal repo
```
remote: Permission to coreui/coreui-free-react-admin-template.git denied to Zainab-Fahim.    
fatal: unable to access 'https://github.com/coreui/coreui-free-react-admin-template.git/': The requested URL returned error: 403
```

Would appreciate relavent input on ways to solve this issue

**Comment by xidedix** [comment]
@Zainab-Fahim you're trying to push into our public repo, not your private one.  You can change remote that you are tracking with your local repository: https://github.com/git-guides/git-remote 
Probably your origin points to our repo.

See also: https://docs.github.com/en/get-started/quickstart/fork-a-repo
