### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by netiapaul** [coreui/coreui-free-react-admin-template#393]
# CoreUI Free React Admin Template v4

$ npm run build

> XXXXXXXXX@4.1.1 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/scss/style.scss
ParserError: Syntax Error at line: 1, column 39

**Comment by HyunjiEllenPak** [comment]
Hi, I had the same issue when building for production.
@netiapaul Did you solve the issue?

**Comment by jamaluddin7** [comment]
> Hi, I had the similar issue.
> 
> After finishing running "npm run build" successfully on this app, empty web screen is shown and the error message "uncaught syntaxError: Unexpected token '<' " is shown. How can I solve it?
Hi, Change your "homepage": ".", to "homepage": "/", in package.json
