### ISSUE TITLE
Failed to compile on npm build

### ISSUE THREAD

**Issue by jamaluddin7** [coreui/coreui-free-react-admin-template#395]
Hi,
Suddenly i am facing an issue with my coreui 4.1.1 project. It runs fine on local machine, when i build the project for server deployment it fails with following error,
```
Failed to compile.

./src/scss/style.scss
ParserError: Syntax Error at line: 1, column 62
```

the same project is building on another machine with identical configs.
node 18

**Comment by mrholek** [comment]
Please update our dependencies to the latest versions

    "@coreui/chartjs": "^3.0.0",
    "@coreui/coreui": "^4.2.1",
    "@coreui/icons": "^2.1.0",
    "@coreui/icons-react": "^2.1.0",
    "@coreui/react": "^4.3.1",
    "@coreui/react-chartjs": "^2.1.0",
    "@coreui/utils": "^1.3.1",
