### ISSUE TITLE
Config url #

### ISSUE THREAD

**Issue by levudangnguyen291119** [coreui/coreui-free-react-admin-template#409]
Hi!
i see all url have contain #. example: http://localhost:3000/#/theme/typography
how to replace http://localhost:3000/#/theme/typography => http://localhost:3000/theme/typography
thanks!

**Comment by BrunoCCPires** [comment]
@levudangnguyen291119, you need to change the Router provider.

At src > App.js you can change the HashRouter for BrowserRouter.

`import React, { Component } from "react";
import { Provider } from "react-redux";
import { HashRouter, BrowserRouter, Route, Switch, Redirect } from "react-router-dom";
import "./scss/style.scss";
import { store, persistor } from "./store";
import { PersistGate } from "redux-persist/integration/react";
import { ErrorBoundary } from "react-error-boundary";
import ErrorBoundaryFallback from "src/components/ErrorBoundary";
import { useHistory } from "react-router-dom";

const loading = (
  <div className="pt-3 text-center">
    <div className="sk-spinner sk-spinner-pulse"></div>
  </div>
);

// Containers
const TheLayout = React.lazy(() => import("./containers/TheLayout"));

// Email App
const TheEmailApp = React.lazy(() => import("./views/apps/email/TheEmailApp"));

// Pages
const Login = React.lazy(() => import("./views/pages/login"));
const Register = React.lazy(() => import("./views/pages/register/Register"));
const Page404 = React.lazy(() => import("./views/pages/page404/Page404"));
const Page500 = React.lazy(() => import("./views/pages/page500/Page500"));

const App: React.FC = () => {
  const history = useHistory();

  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <BrowserRouter history={history}>
        {/* <HashRouter> */}
          <ErrorBoundary FallbackComponent={ErrorBoundaryFallback}>
            <React.Suspense fallback={loading}>
              <Switch>
                <Route
                  exact
                  path="/login"
                  name="Login"
                  render={(props) => <Login {...props} />}
                />
                <Route
                  path="/"
                  name="Home"
                  render={(props) => <TheLayout {...props} />}
                />
              </Switch>
            </React.Suspense>
          </ErrorBoundary>
        {/* </HashRouter> */}
        </BrowserRouter>
      </PersistGate>
    </Provider>
  );
}

export default App;
`

**Comment by Jyotiprakash-Redapple** [comment]
in core Ui use Hash Route So it is look like api/v1/typography#/....
..You need to change it to browserRouter
