### ISSUE TITLE
Sidebar with nav-dropdown-items open defaultly

### ISSUE THREAD

**Issue by ladislavbili** [coreui/coreui-free-react-admin-template#41]
Hi, I am currently working with core-ui pro version, using react-js. I would like to know, how can I set that items/parents (that have some other links in them) to be opened defaultly. For example, in your demo http://coreui.io/demo/pro/Ajax_Demo/#main.html this would mean, that i can set for example Components ,Icons and Widgets to be opened by default (their children links are shown, in case of Components parent link it would be Buttons,Cards,Modals etc.).
Thank you in andvance.

**Comment by woothu** [comment]
In version 3 `CSidebarNavDropdown` component has `show` prop. Moreover, there are multiple dropdownModes (default behaviors) to set in CSidebar component. Check it out!
