### ISSUE TITLE
Clean install. Navigation (buttons do not work).

### ISSUE THREAD

**Issue by ATouhou** [coreui/coreui-free-react-admin-template#416]
Windows 11 (latest update).
(Tested in Opera and Firefox. Same)
I can copy the navigation url (example: http://localhost:3000/#/theme/typography ) and site exists.  However as I said. Buttons in menu navigation on the left do not work. No errors in console.

Before opening:
------------------------
- [Search for duplicate or closed issues](https://github.com/coreui/coreui-free-react-admin-template/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/coreui/coreui-free-react-admin-template/blob/v4-dev/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS)
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by ATouhou** [comment]
```
[Download the latest release](https://github.com/coreui/coreui-free-react-admin-template/archive/refs/heads/main.zip)
Clone the repo: git clone https://github.com/coreui/coreui-free-react-admin-template.git
```
The download the latest release works as intended. Links are clickable.
It's the clone the repo version that does not work :)

**Comment by alexander-sorokin** [comment]
> The "download the latest release" works as intended. Links are clickable.
> It's the "clone the repo" version that does not work :)

Latest release is v4.
I tried few commits from v5 branch but could not find any working.
