### ISSUE TITLE
Charts tooltip doesn't have any style

### ISSUE THREAD

**Issue by ArekkMirmun** [coreui/coreui-free-react-admin-template#420]
- Ubuntu 22.04 LTS
- Browser tested: Brave (Chrome based), Firefox and Chrome.

Description
Charts tooltip doesn't have the format that it had in older versions.
It looks like the style provided in variable.scss does not apply correctly.
I am able to solve it temporary by adding all the following styles manually to custom.scss

```
// Custom tooltips

.chartjs-tooltip {
  position: absolute;
  z-index: $zindex-sticky + 1;
  padding: ($spacer * .25) ($spacer * .5);
  color: #fff;
  pointer-events: none;
  background: rgba(0, 0, 0, .7);
  opacity: 0;
  @include transition(all .15s ease);
  transform: translate(-50%, 0);
  @include border-radius($border-radius);
}

.chartjs-tooltip-header {
  margin-bottom: ($spacer * .5);
}

.chartjs-tooltip-header-item {
  font-size: $font-size-sm;
  font-weight: $font-weight-bold;
}

.chartjs-tooltip-body-item {
  align-items: center;
  font-size: $font-size-sm;
  white-space: nowrap;
}
```

Screenshots [Older Versions of CoreUI]
![image](https://github.com/coreui/coreui-free-react-admin-template/assets/123628854/5b0f00bb-13e9-4b9c-8e0e-c849527fbbff)
![image](https://github.com/coreui/coreui-free-react-admin-template/assets/123628854/19e51f71-1fbe-45d3-b5f1-3b796d95a110)
![image](https://github.com/coreui/coreui-free-react-admin-template/assets/123628854/5a1225f3-85d4-4831-9a79-4f92d5a10d6e)

[Version 5 of CoreUI]
![image](https://github.com/coreui/coreui-free-react-admin-template/assets/123628854/52df85a7-7180-46fe-b5c8-957f49af1300)
![image](https://github.com/coreui/coreui-free-react-admin-template/assets/123628854/592066a8-6429-493f-81f8-3df94805c584)
![image](https://github.com/coreui/coreui-free-react-admin-template/assets/123628854/4fd41d1b-c32d-4b2c-ac89-9a534f75e3be)

To Reproduce
Clone repository

npm install

npm start

**Comment by mrholek** [comment]
@ArekkMirmun, in the latest commit, I fixed it.
