### ISSUE TITLE
Error (invalidProjectName) when attempting to setup application for AWS onboarding.

### ISSUE THREAD

**Issue by Queen-Geek** [coreui/coreui-free-react-admin-template#431]
![image](https://github.com/user-attachments/assets/6b48d6a5-ec3b-4735-b64c-36bd66dc1177)

Attempting to run ng build --prod --base-href to onboard this application to AWS, but I'm getting the error above. Is anyone aware of the cause?

Bug reports must include:
Operating System: Windows 11
Browser: Microsoft Edge Version 129.0.2792.89 ; However, the error is in Visual Studio code, this is only the browser I'm using to post this.

**Comment by mrholek** [comment]
@Queen-Geek, do you use the React.js version or Angular because `ng build --prod --base-href` is an Angular command?
