### ISSUE TITLE
how to download free template

### ISSUE THREAD

**Issue by vishnuprabhu-g** [coreui/coreui-free-react-admin-template#47]
How to download free template or the template is available only for the paid users?

**Comment by xidedix** [comment]
hi @vishnuprabhu-g 
````
git clone https://github.com/coreui/coreui-free-react-admin-template.git
````
or download and unzip archive:
https://github.com/coreui/coreui-free-react-admin-template/archive/master.zip
see also:
https://github.com/coreui/coreui-free-react-admin-template#installation
