### ISSUE TITLE
App starts on incorrect port

### ISSUE THREAD

**Issue by donalmurtagh** [coreui/coreui-free-react-admin-template#48]
According to the README.md in each project, the app should start on port 3000 when you run `npm start`, but it actually starts on port 8080.

**Comment by xidedix** [comment]
hi @donalmurtagh 
you are right, `webpack-dev-server` is configured by default  to listen for connections from `localhost` on port `8080` (it used to be 3000 - before ejecting from [Create React App](https://github.com/facebook/create-react-app)'s build scripts)

**Comment by donalmurtagh** [comment]
@xidedix I guess either the docs or the dev server config should be changed to make them consistent

**Comment by xidedix** [comment]
@donalmurtagh 
on v2 we are back to default port `3000` with not ejected `create-react-app`

**Comment by xidedix** [comment]
I'm closing this since it appears to be answered above.
