### ISSUE TITLE
Linting?

### ISSUE THREAD

**Issue by kershnerd** [coreui/coreui-free-react-admin-template#49]
I purchased the pro react version and I believe this template was created with the react-create-app.  How do I enable linting?  Is this not built in?

Thanks...

**Comment by wuno** [comment]
@kershnerd can you verify that if you buy the pro version it is indeed made with create react app? I know when you use the React_Full_Project it is not. So I would be super surprised if the paid version is. 

Also may I suggest you just install eslint to the project? It takes about 3 minutes to setup.

**Comment by xidedix** [comment]
v2 is made with create-react-app and includes eslint
