### ISSUE TITLE
Sidebar toggle problem in RTL mode ( mobile dimension)

### ISSUE THREAD

**Issue by buglessir** [coreui/coreui-free-react-admin-template#55]
Hi, I set html direction to rtl for a right to left layout. But in mobile version I have this problem :

- the sidebar is not closed by default
- the additional right padding for dashboard menu link
- the logo is not at right place and this have a border-bottom

![bug2](https://user-images.githubusercontent.com/23656061/36418330-ceb1fa0a-1643-11e8-8735-020e24a5bea4.jpg)

Consider I downloaded the latest version and i using Reactjs

**Comment by ahmad7485** [comment]
hi you can use media query for solve it
