### ISSUE TITLE
.babelrc file vs babel-loader options

### ISSUE THREAD

**Issue by brownieboy** [coreui/coreui-free-react-admin-template#56]
I was trying to add the transform-class-properties plugin to the .babelrc file, but webpack kept telling me that it was missing when I tried to run my app in the browser.

After a lot of head scratching and Googling, I realised that webpack was actually ignoring the .babelrc file in favour of the babel-loader options defined in the webpack.config.js file, i.e:
```
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
              presets: ['react', 'env']
            }
          }
        },
```

This needs to be one or the other, doesn't it?  If we're not using the .babelrc file, then why is one supplied in the set up?

I was able to work around the issue by removing the presets from the webpack.config.js file and setting the babelrc option there to true, like so:
```
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
            options: {
              cacheDirectory: true,
              babelrc: true
            }
          }
        },
```

Webpack then picked up the transform-class-properties plugin from my .babelrc file.

**Comment by xidedix** [comment]
Thanks @brownieboy good find!
