### ISSUE TITLE
suggestion for v2

### ISSUE THREAD

**Issue by scheiblr** [coreui/coreui-free-react-admin-template#64]
Hi guys, 

thanks for this beautiful and useful admin theme. v2 looks cleaner than v1, but to the cost of some flexibility to devs, if 'eject' is no option.

Thus, I suggest to use [custom-react-scripts ](https://github.com/kitze/custom-react-scripts) which offers some configuration options.

Kind regards

**Comment by xidedix** [comment]
hi @scheiblr 
Thanks for the hint, we’ll look into it.

**Comment by aghamir** [comment]
Hi,
You can see [this repo](https://github.com/monkey-patches/monkey-react-scripts) too.

**Comment by scheiblr** [comment]
[This](https://github.com/timarney/react-app-rewired) looks usable and easy to extend. Would probably easy the less-usage as well..
