### ISSUE TITLE
npm test error

### ISSUE THREAD

**Issue by aghamir** [coreui/coreui-free-react-admin-template#65]
- OS version: Ubuntu1604
I've run ``yarn test`` and this is the output:
![image](https://user-images.githubusercontent.com/1880925/38976555-d549e656-43c6-11e8-8b29-aa34a57f0931.png)

**Comment by xidedix** [comment]
hi @aghamir 
please include log file - with the screenshot it is not possible to determine which tests failed

**Comment by aghamir** [comment]
Hi @xidedix ,
Sorry for opening issue and respond too late. I've updated my nodejs and everything was ok.
So I close this issue.
Thank a lot
