### ISSUE TITLE
Showing sidebar items by roles

### ISSUE THREAD

**Issue by nycoh** [coreui/coreui-free-react-admin-template#67]
First i want to say this template is really nice, my thing is i want to show the items on the sidebar deping on redux state for user roles, somthing like if((this.state.user.rol).includes('admin'){
///... show side var items
}

**Comment by anantadwi13** [comment]
you can create your new navbar item list in `src/_nav.js`. 
```js
const customNav1 = {
  items: [
    {
      name: 'Dashboard',
      url: '/dashboard',
      icon: 'icon-speedometer',
      badge: {
        variant: 'info',
        text: 'NEW',
      },
    },
  ]
};
```
then import it to `src/containers/DefaultLayout/DefaultLayout.js` by changing few codes

``` js
//from
import navigation from '../../_nav';
//to
import {customNav1, customNav2} from '../../_nav';
```

then in render method, add some logic before return statement

``` js
if (isAdmin)
  navigation = customNav1;
else
  navigation = customNav2;
```

**Comment by axle21** [comment]
> you can create your new navbar item list in `src/_nav.js`.
> 
> ```js
> const customNav1 = {
>   items: [
>     {
>       name: 'Dashboard',
>       url: '/dashboard',
>       icon: 'icon-speedometer',
>       badge: {
>         variant: 'info',
>         text: 'NEW',
>       },
>     },
>   ]
> };
> ```
> 
> then import it to `src/containers/DefaultLayout/DefaultLayout.js` by changing few codes
> 
> ```js
> //from
> import navigation from '../../_nav';
> //to
> import {customNav1, customNav2} from '../../_nav';
> ```
> 
> then in render method, add some logic before return statement
> 
> ```js
> if (isAdmin)
>   navigation = customNav1;
> else
>   navigation = customNav2;
> ```

you need to insert export in front of const customNav1 and const customNav2 in order to export it

**Comment by axle21** [comment]
thanks so much @anantadwi13 , just need to put export for a variable to be exported in _nav
