### ISSUE TITLE
Not able to run the react project

### ISSUE THREAD

**Issue by parikh-nisarg** [coreui/coreui-free-react-admin-template#72]
I just cloned React core ui project, while npm install I am getting this following error for all versions.

![image](https://user-images.githubusercontent.com/13731429/39230384-ec7ea93a-4883-11e8-9c90-3c28dbacc654.png)

**Comment by xidedix** [comment]
hi @parikh-nisarg 
cannot reproduce, please try:

- remove `node_modules` directory
- remove `package-lock.json` file
- run `npm cache clean --force`
- then `npm install`

**Comment by xidedix** [comment]
I'm closing this since it appears to be answered above and is no longer active. Please comment and/or reopen if you feel the issue has not been resolved.
