### ISSUE TITLE
Mobile sidebar does not close when tapping outside of the navbar

### ISSUE THREAD

**Issue by JamesSingleton** [coreui/coreui-free-react-admin-template#74]
Just an overall question, but I noticed that on Mobile, the sidebar that slides over everything does not close if you tap outside of the sidebar. However, if you tap on the user Avatar and then tap outside of that, it closes. Is there a way to get the sidebar to have the same treatment?

**Comment by xidedix** [comment]
Hi @JamesSingleton 
one of possibilities is `document.addEventListener` to capture `click` or `touchstart` outside Sidebar container. 
Any other ideas?

**Comment by JamesSingleton** [comment]
@xidedix,

Yea that could work. I don't exactly know how bootstrap does their dropdown/dropdown menu.

Or something like this?
```
showMenu(event) {
    event.preventDefault();
    
    this.setState({ showMenu: true }, () => {
      document.addEventListener('click', this.closeMenu);
    });
  }
  
  closeMenu() {
    this.setState({ showMenu: false }, () => {
      document.removeEventListener('click', this.closeMenu);
    });
  }
```

**Comment by JamesSingleton** [comment]
@xidedix ,

It looks like I can't assign this to myself but I have made a pull request to address this.

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Comment by carlospauluk** [comment]
Still not working!

**Comment by xidedix** [comment]
@carlospauluk which version?
