### ISSUE TITLE
Import/first error

### ISSUE THREAD

**Issue by vpn1997** [coreui/coreui-free-react-admin-template#78]
![screenshot 6](https://user-images.githubusercontent.com/17298412/39885517-69eb5008-54aa-11e8-8d70-9613f7261266.png)
- This error pops up whenever i do any code changes in containers section and then try to re-start the server.

**Comment by xidedix** [comment]
Hi @vpn1997

Looks like you accidentally installed `React Popper` into `./src/containers/DefaultLayout` directory. So the linter thinks it’s your code and tries to validate it. Don’t install third party dependencies inside `src`.

Delete `node_modules` dir and run `npm install` in the **root directory** of your app.

**Comment by vpn1997** [comment]
Hey @xidedix 

The node_module dir automatically gets generated whenever i stop the server and then restart it. So deleting it every time is not an efficient solution.
You can try to reproduce this error -
1.Install  coreUI.
2.Run `npm start`
3.Stop the server and do some changes in containers dir.
4.Restart the server.You will find it automatically creates node_module dir.

**Comment by xidedix** [comment]
@vpn1997 
- Cannot reproduce, but there is no magic, `npm start` doesn't run `npm install`.  Something goes wrong with your webpack configuration, I suppose. What's in your main package.json file?
- Do you have any dependencies in `./src/containers/DefaultLayout/package.json` and so on?
- Why do you stop dev server btw? It works with HMR by default - the page will reload if you make edits.

**Comment by vpn1997** [comment]
@xidedix 
 - I have not updated my main pacage.json file so .
 - Yeah 
![image](https://user-images.githubusercontent.com/17298412/39927911-611b88ce-5551-11e8-8ef1-afb4ae4ff92f.png)
- I know that but stopping the server shouldn't perigee any problem.

btw i have creating a small video of reproducing the bug.
https://drive.google.com/file/d/1e2QXyxa00a7xpmn5VGfGuAFG5aw3T_fI/view
Have a look at it(2x recommended).
Thanks!

**Comment by xidedix** [comment]
@vpn1997 
1. remove all `dependencies` from `./src/containers/DefaultLayout/package.json`  
or revert to default value:
````js
{
  "name": "Full",
  "version": "0.0.0",
  "private": true,
  "main": "./Full.js"
}
````
2. remove `package-lock.json` file 
3. remove `node_modules` dir
3. `cd ~/my-project`
4. run `npm install`
5. run `npm start`

I hope this helps

**Comment by vpn1997** [comment]
- Hey sorry but it didnt help me ! :cry: 
- First of all changing the  `package.json` file didnt help cuz it gets updated/replaced whenever i make any change and restart the server(dependencies gets added).
- `node modules` also gets created therefore and then the same error pops up.
@xidedix Need your help !

**Comment by xidedix** [comment]
@vpn1997 that's  strange, could you start from the scratch to see if this behavior persists?
- clone repo to the new, empty dir
- npm install
- npm start
- modify some code 
- let us know how it went

**Comment by vpn1997** [comment]
- Here  https://drive.google.com/file/d/1IGsfiKQBceiq5kxXxPDzZLVQGYncBElA/view 
- Its a 7 min video. I have reproduce the same error with a fresh new copy of coreUI. I have also made the changes you asked but as you will see , they weren't of much use :smile: .

**Comment by xidedix** [comment]
@vpn1997 
Still cannot reproduce... :worried:
What's your node.js version?
````bash
$ node -v
````

**Comment by vpn1997** [comment]
Specifications -
- node  8.3.0
- npm 5.3.0
- OS : Ubuntu 17.04

**Comment by vpn1997** [comment]
Damn  `npm cache clean` saved me . A day of debugging ends with this :heart:  .
Thank you so much @xidedix  :heart: .

**Comment by vpn1997** [comment]
Moral of the story, when something seems fishy with a module you are installing, you’ve tried everything and nothing else seems to work, clear you cache! It might save you from switching professions.

**Comment by xidedix** [comment]
@vpn1997
I’m glad you got that sorted out!
