### ISSUE TITLE
How sidebar is managed, replacing Simple Line Icons

### ISSUE THREAD

**Issue by adrien3d** [coreui/coreui-free-react-admin-template#80]
Hi,

I would like to know how the sidebar is managed (i.e HTML code).

Because all I can see is some classes in `style.css`, and a structure in `_nav.js`.

Can you tell me how the code is handled from the items in `_nav.js`?

I would like to change icons because Simple Line Icons are fairly limited, how can I do this?

Thank you,
Regards,
Adrien

**Comment by xidedix** [comment]
hi @adrien3d 
to change sidebar icons , modify `icon` property of sidebar item in `_nav.js`, for example:
````javascript
{
  name: 'Dashboard',
  url: '/dashboard',
  icon: 'fa fa-book',
  badge: {
  variant: 'info',
  text: 'NEW',
  },
},
````

**Comment by adrien3d** [comment]
Thanks for the quick reply.
What version of font-awesome is included?
How it is included? Is it simple to upgrade? (I would like to use new icons that requires 5.0.9)

**Comment by xidedix** [comment]
I'm closing this since it appears to be answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Comment by SiriLivtar** [comment]
Hi, 
Can I change font-awesome icons for SVG icons?
I am trying to do this, but I have not been able to do it.

Thank you, 
Regards,
Luis

**Comment by kid-three** [comment]
> Can I change font-awesome icons for SVG icons?

Just like @SiriLivtar I need to use my own custom svg icons.. but it seems that the current system only adds class names to an <i> element

**Comment by fmandres92** [comment]
Hello everybody. Is possible add my own custom svg icons. Please if you can help me with this. Thanks
