### ISSUE TITLE
[Question] : How to integrate CoreUi with an existing React Application.

### ISSUE THREAD

**Issue by vpn1997** [coreui/coreui-free-react-admin-template#81]
- Hey I am planning to add CoreUI admin template for my opensource project ( https://github.com/Cloud-CV/Origami ) .So I need to know what is the workflow i should follow in order do so(or if there's any documentation available ?). This documentation was not really helpfull (https://coreui.io/docs/admin-templates/react-admin/). 
Thanks!

**Comment by xidedix** [comment]
There is no single best way to do it, because existing projects have varied structures. You have to create your own views or components and manually incorporate them into CoreUI template (views, routings, navigation).

**Comment by vpn1997** [comment]
- So what  i did was to install coreui into a separate directory inside my project folder. Then I imported bunch of components from it  and set my routes accordingly . But when i start my application , there was bunch of CORS error.

My question( might sound silly but i am not that experienced in React in general) -
-  What should i do so that my react application and this coreui runs together.How should i modify package.json scripts of my core application so that coreUi runs smoothly with it etc(I know ill need to add coreui dependencies in it ). [Project link]( https://github.com/Cloud-CV/Origami ).
You can have a look at the project structure. 

project script -

![screenshot 6](https://user-images.githubusercontent.com/17298412/40095984-4d311470-58ec-11e8-9a9e-dd4e54496e87.png)

@xidedix 
Thanks!

**Comment by devg02** [comment]
@vpn1997 did you figure out a way to do this?
