### ISSUE TITLE
E404 When running npm install on full-project pro

### ISSUE THREAD

**Issue by muchenbit** [coreui/coreui-free-react-admin-template#82]
Just bought the PRO version with standard license, and received the `react-full-project-v2.0.2`.

When running `npm install` I run into the following error:

`npm ERR! 404 Not Found: @coreui/coreui-pro@^2.0.1`

I'm wondering if this package no longer exists and needs to be changed in the package.json?

**Comment by muchenbit** [comment]
I ran it a third time and it seemed to work. Could you explain the issue that might have occurred?

**Comment by xidedix** [comment]
there were some issues with npm publish on this version 
please update to `@coreui/coreui-pro@^2.0.4`
