### ISSUE TITLE
Error in console when clicking on the same navigation item

### ISSUE THREAD

**Issue by skydiver** [coreui/coreui-free-react-admin-template#88]
**Specs:**
OS: macOS
Browser: Chrome & Firefox

**Problem:**
I get following error when clicking on the active navigation item:

`Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack`.

**Steps to reproduce:** 
1. clone repo
2. npm install
3. npm start
4. click on any navigation item like "Colors"
5. click again on same item
6. console will show the error

**Comment by JamesSingleton** [comment]
@skydiver,

This is just a warning not necessarily an error. My guess is you are running this in development mode not production; in production you shouldn't get this error. I found this GitHub issue that talks about it https://github.com/ReactTraining/react-router/issues/4467. 

This is a quote from the issue

> 
> The warning is there just to let you know that when you're using hash history, you can't actually PUSH the same path; the browser won't add anything to the history stack.
> 
> But you should only get this warning in development. If you generate your production build correctly (using NODE_ENV=production) you shouldn't see this warning in production.

**Comment by skydiver** [comment]
Thanks @JamesSingleton 

Yes, doesn't show the error on production.
