### ISSUE TITLE
Change Theme

### ISSUE THREAD

**Issue by rfaloisio** [coreui/coreui-free-react-admin-template#92]
Hey Guys! 

Sorry for the stupid question, but I am only beggining with JS and CoreUI.

I'm trying to find where to change the colors of the theme, but no success. 

Thanks in advance!

**Comment by JamesSingleton** [comment]
Hi @rfaloisio,

So looking at the style.css file, it doesn't look like they have an inherit dark theme or a toggle. You would have to go in an manually override the values that come with the style.css file yourself. Also, according to their website, the Dark Theme comes with the pro version.

**Comment by skydiver** [comment]
Got the pro version, how i can use the dark theme?
Docs doesn't suggest anything ...

**Comment by xidedix** [comment]
@skydiver 
see: `src/scss/style.scss`

**Comment by skydiver** [comment]
If anyone needs help on this, i've changed line 5 on `src/scss/style.scss` from:

`@import "@coreui/coreui-pro/scss/coreui.scss";`
to
`@import "@coreui/coreui-pro/scss/themes/dark/coreui-dark.scss";`

Strange this feature is not on the docs...

**Comment by xidedix** [comment]
@skydiver theme toggling is subject to change, hence it's not in the docs yet
you can find the description in comments  `src/scss/style.scss`

**Comment by xidedix** [comment]
I'm closing this since it appears to be answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Comment by rfaloisio** [comment]
Hey Guys! 

I'm a little late on the answer.

I tried changing the variables on src/scss/styles.css but my changes get overwritten by another file from node_modules.
How can I put the values i'm inserting as 'default'?

**Comment by llakhani** [comment]
@xidedix 
But Mine is not react.. mine is bootstrap template only.. I have purchased from https://coreui.io/pro/

**Comment by xidedix** [comment]
@llakhani it's the same, you have to rebuild 
https://github.com/coreui/coreui-free-bootstrap-admin-template#usage

**Comment by llakhani** [comment]
@xidedix : thank you thank you!!! It worked for me!!! Saved my day 👍

**Comment by xidedix** [comment]
@llakhani I'm glad you've got it sorted out :)

**Comment by marsanaemi** [comment]
hello
i was trying to override layer.scss file in coreui vue template to change page style i wrote my css in custom.scss file but some of them are applied and some of them didnt .
actually i copied all layer.scss in custom.scss and change the part that i want to
