### ISSUE TITLE
Add event listeners on Sidebar. 

### ISSUE THREAD

**Issue by vpn1997** [coreui/coreui-free-react-admin-template#96]
* Hey How to add event listeners(like on Click etc) on `AppAside`(Right side slide bar).I tried to add onClick listener but its not working.

**Comment by xidedix** [comment]
hi @vpn1997 
Could you explain more, what do you want to achieve with event listeners here?

**Comment by vpn1997** [comment]
Hey @xidedix  I want to do some state changes whenever use clicks on the slidebar icon.

**Comment by xidedix** [comment]
Do you mean AsideToggler icon or any other icon/element inside Aside component?

**Comment by vpn1997** [comment]
AsideToggler Icon

**Comment by xidedix** [comment]
@vpn1997 
here is a dirty solution 
- modify `src/containers/DefaultLayout/DefaultHeader.js` like this:

```js
// add ReactDOM import 
import ReactDOM from 'react-dom';
//...
class DefaultHeader extends Component {
  constructor(props) {
    super(props);
    this.asideTogglerRef = React.createRef();
  }

  componentDidMount() {
    ReactDOM.findDOMNode(this.asideTogglerRef.current).addEventListener('click', this.handleClick);
  }

  componentWillUnmount() {
    ReactDOM.findDOMNode(this.asideTogglerRef.current).removeEventListener('click', this.handleClick);
  }

  handleClick() {
    console.log('Click')
  }

render() {...}
}
```

**Comment by vpn1997** [comment]
@xidedix thanks for the quick solution.I have another doubt tho.I want to toggle the `<AppSidebarMinimizer />` whenever user click on `AppAsideToggler`.Any workaround?

**Comment by xidedix** [comment]
hi @vpn1997 
Again, there are several ways to do this.
If you have an event listener added, as in the example above, you can simply toggle relevant classes inside `handleClick()` method:
```js
handleClick() {
  document.body.classList.toggle('sidebar-minimized');
  document.body.classList.toggle('brand-minimized');
}
```

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.
