### ISSUE TITLE
Sidebar Dynamic Loading 

### ISSUE THREAD

**Issue by rfaloisio** [coreui/coreui-free-react-admin-template#97]
Hey, Guys!

I'm getting via axios an array of objects with name and id on it.
My question is:

How can I load them dynamically to mount the nav/sidebar when I render my defaultLayout?

Thanks in advance!

**Comment by rfaloisio** [comment]
Because I can't interact with the _nav.js file unless it's to pre-define the list of menu items.

Thats the real question:
How to do it?

**Comment by xidedix** [comment]
hi @rfaloisio 
you can modify `DefaultLayout ` like this:
```js
//... imports omitted for brevity 
class DefaultLayout extends Component {
  constructor(props) {
    super(props);

    this.state = {
      navData: navigation,
    };
  }

  componentDidMount() {
    this.loadSidebar('http://www.json-generator.com/api/json/get/cqaVnnbCjS?indent=2')
  }

  loadSidebar(navUrl) {
    const request = async () => {
      const response = await fetch(navUrl);
      const json = await response.json();
      console.log(json);
      this.setState({ navData: json })
    }

    request();
  }

//... etc 
```

and in `render` method:
```js
<AppSidebarNav navConfig={this.state.navData} {...this.props} />
```

it's only rough draft example, you can use `axios` if you perfer

**Comment by rfaloisio** [comment]
Hi @xidedix !

Thanks for the response. 

Got what you meant, but i'm having another trouble.

The response I get is a json with another structure. The fields are "Id" which is not gonna be used in this function, "ReferenceName" which will be the "name" on the menu, and "CodeId" that will be used on the url field. 

How to map these things up and make it "readable" for the render method?

Thanks again

**Comment by xidedix** [comment]
@rfaloisio 

I had to make some assumptions about your `json` structure.
No magic, just plain js.

```js
const dataIn = [
  {Id: 1, ReferenceName: "Test 1", CodeId: "/test1" }, 
  {Id: 2, ReferenceName: "Test 2", CodeId: "/test2" }, 
  {Id: 3, ReferenceName: "Test 3", CodeId: "/test3" }
]
const items = dataIn.map((item) => { return { name: item.ReferenceName, url: item.CodeId } } )
const jsonOut = Object.create(null)
jsonOut.items = items
console.log(jsonOut)
```

**Comment by rfaloisio** [comment]
Hi, @xidedix !
So, I did this and it came out with an error. 

"TypeError: Cannot read property 'map' of undefined"
```

  getDeviceMenuList = () => {
    var loggedUser = AuthService.getCredentials();
    DevicesService.getDeviceMenuList(loggedUser.id)
      .then((response) => { 
        console.log(response.data.resultado[0]);
        this.setState({navData: response.data.resultado[0]});
        var dataIn = this.state.navData;
        const items = dataIn.map((item) => { return { name: item.ReferenceName, url: '/device', icon: 'fa fa-microchip' } } )
        const jsonOut = Object.create(null)
        jsonOut.items = items
        this.state.navData = items;
        console.log(this.state.navData)
       
      })
      .catch((error) => {
        console.log(error);
      });
```

And on the render function, I've put this:

`<AppSidebarNav navConfig={this.state.navData} {...this.props} />`

Any ideas?

**Comment by xidedix** [comment]
@rfaloisio 
not tested:
```js
.then((response) => { 
  const dataIn = response.data.resultado[0];
  const jsonOut = Object.create(null)
  jsonOut.items = dataIn.map((item) => {
    return { name: item.ReferenceName, url: '/device', icon: 'fa fa-microchip' }
  } )
  this.setState({navData: jsonOut})
}) 
```

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive and answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Comment by joseferrer1090** [comment]
Hello, good afternoon from Colombia, I need to make my _nav file of my AppSidebarNav have internationalization with react-i18next, I am not using typescript how could I add it so that the menu changes depending on the language selection

**Comment by kheipl** [comment]
I also loaded sidebar dynamically from API.I would like to know how to load "routes" dynamically from api.
