### ISSUE TITLE
Communication between sidebar and other JS file 

### ISSUE THREAD

**Issue by OB96** [coreui/coreui-free-react-admin-template#98]
Hello, it's my first issue, thank you for this fabulous project,
i am beginner on react
i dont know how can i get in Tabs.js an item choosed (clicked) from the sidebar (left one) 
can anyone help me please ?

**Comment by woothu** [comment]
This is not related to our library. Since then we created our own Tabs component in v3 https://coreui.io/react/docs/components/CTabs
