### ISSUE TITLE
Error when accessing /theme/colors on Microsoft Edge

### ISSUE THREAD

**Issue by CaoHoangTung** [coreui/coreui-free-react-admin-template#99]
After cloning the template to my laptop and downloaded all the dependencies, I accessed http://localhost:3000/#/theme/colors and had the following error

**Error: transparent is not a valid rgb color**

My browser is Microsoft Edge 42.17134.1.0. The same thing happened when accessing on IE. BUT it worked normally on Firefox and Google Chrome

**Comment by woothu** [comment]
Is this still an issue?
